---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: contract-manager-application-service
  name: contract-manager-application-service
  namespace: contract-manager
spec:
  ports:
  - name: contract-manager-backend
    port: 4000
    protocol: TCP
    targetPort: 4000
  - name: contract-manager-frontend
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: contract-manager-application-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
