apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: template-sandbox-application-service
  name: template-sandbox-application-service
  namespace: {{ .Values.template_sandbox.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-sandbox-application-service
  template:
    metadata:
      labels:
        app: template-sandbox-application-service
    spec:
      containers:
      - name: template-sandbox-backend
        image: {{ .Values.mainRepo }}/template-sandbox-backend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.template_sandbox.backendPort }}
        env:
        - name: GITHUB_BASE_URL
          value: https://api.github.com/repos/IndustryFusion/templates/contents/new-temp
        - name: GITHUB_TOKEN
          value: {{ .Values.template_sandbox.githubToken }}
        - name: S3_URL
          value: s3-eu-central-1.ionoscloud.com
        - name: S3_ACCESS_KEY
          value: {{ .Values.template_sandbox.s3AccessKey }}
        - name: S3_SECRET_KEY
          value: {{ .Values.template_sandbox.s3SecretKey }}
        - name: S3_BUCKET
          value: iff-dev
        - name: USERNAME
          value: {{ .Values.template_sandbox.username }}
        - name: PASSWORD
          value: {{ .Values.template_sandbox.password }}
        - name: MONGO_URL
          value: {{ .Values.template_sandbox.mongoUrl }}
      - name: template-sandbox-frontend
        image: {{ .Values.mainRepo }}/template-sandbox-frontend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.template_sandbox.frontendPort }}
        env:
        - name: NEXT_PUBLIC_BACKEND_API_URL
          value: https://dev-sandbox-backend.industry-fusion.com
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
