apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ifric-platform-application-service
  name: ifric-platform-application-service
  namespace: {{ .Values.ifric_platform.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifric-platform-application-service
  template:
    metadata:
      labels:
        app: ifric-platform-application-service
    spec:
      containers:
      - name: ifric-platform-backend
        image: {{ .Values.mainRepo }}/ifric-platform-backend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ifric_platform.backendPort }}
        env:
        - name: GITHUB_BASE_URL
          value: https://api.github.com/repos/IndustryFusion/templates/contents/new-model
        - name: GITHUB_TOKEN
          value: {{ .Values.ifric_platform.githubToken }}
        - name: CORS_ORIGIN
          value: https://dev-platform.ifric.org
        - name: IFRIC_REGISTRY
          value: https://dev-registry.ifric.org
      - name: ifric-platform-frontend
        image: {{ .Values.mainRepo }}/ifric-platform-frontend:{{ .Values.mainVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ifric_platform.frontendPort }}
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          value: https://dev-platform-backend.ifric.org
        - name: NEXT_PUBLIC_DPP_CREATOR_IP
          value: https://dev-dpp-creator.ifric.org
        # volumeMounts:
        # - name: nginx-config
        #   mountPath: /etc/nginx/conf.d/default.conf
        #   subPath: default.conf
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
      # volumes:
      # - name: nginx-config
      #   configMap:
      #     name: if50-nginx
      #     items:
      #     - key: config
      #       path: default.conf
