apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ifric-platform-application-service
  name: ifric-platform-application-service
  namespace: {{ .Values.ifric_platform.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifric-platform-application-service
  template:
    metadata:
      labels:
        app: ifric-platform-application-service
    spec:
      containers:
      - name: ifric-platform-backend
        image: {{ .Values.mainRepo }}/ifric-platform-backend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ifric_platform.backendPort }}
        env:
        - name: GITHUB_BASE_URL
          value: https://api.github.com/repos/IndustryFusion/templates/contents/new-temp
        - name: GITHUB_TOKEN
          value: {{ .Values.ifric_platform.githubToken }}
        - name: GITHUB_ERP_URL
          value: https://api.github.com/repos/IndustryFusion/templates/contents/erp-field-maps
        - name: SCORPIO_URL
          value: https://dev-dataroom.ifric.org/ngsi-ld/v1/entities
        - name: S3_URL
          value: s3-eu-central-1.ionoscloud.com
        - name: S3_ACCESS_KEY
          value: {{ .Values.ifric_platform.s3AccessKey }}
        - name: S3_SECRET_KEY
          value: {{ .Values.ifric_platform.s3SecretKey }}
        - name: S3_BUCKET
          value: iff-dev
        - name: USERNAME
          value: {{ .Values.ifric_platform.username }}
        - name: PASSWORD
          value: {{ .Values.ifric_platform.password }}
        - name: ICID_SERVICE_BACKEND_URL
          value: https://dev-icid-service.ifric.org
        - name: CORS_ORIGIN
          value: {{ .Values.ifric_platform.corsOrigin }}
        - name: ASSETS_DEFAULT_CODE
          value: IFX-EUR-NLD-AST
        - name: USERS_DEFAULT_CODE
          value: IFX-EUR-NLD-USR
        - name: CONTEXT
          value: https://industryfusion.github.io/contexts/tutorial/v0.1-dev/context.jsonld
        - name: MONGO_URL
          value: {{ .Values.ifric_platform.mongoUrl }}
        - name: IFRIC_REGISTRY_BACKEND_URL
          value: https://dev-registry.ifric.org
        - name: TEMPLATE_SANDBOX_BACKEND_URL
          value: https://dev-sandbox-backend.industry-fusion.com
        - name: IFX_PLATFORM_SCORPIO_URL
          value: 212.132.81.11:9090
        - name: JIRA_URL
          value: https://ib-systems.atlassian.net/rest/api/3
        - name: JIRA_TOKEN
          value: {{ .Values.ifric_platform.jiraToken }}
        - name: EMAIL_URL
          value: https://graph.microsoft.com/v1.0
        - name: CLIENT_ID
          value: {{ .Values.ifric_platform.clientId }}
        - name: CLIENT_SECRET
          value: {{ .Values.ifric_platform.clientSecret }}
        - name: TENANT_ID
          value: {{ .Values.ifric_platform.tenantId }}
        - name: IFX_PLATFORM_BACKEND_URL
          value: https://dev-platform-backend.industryfusion-x.org
        - name: ZOHO_DESK_ORGANIZATION_ID
          value: 20101939812
        - name: ZOHO_DEPARTMENT_ID
          value: 186093000000007061
      - name: ifric-platform-frontend
        image: {{ .Values.mainRepo }}/ifric-platform-frontend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ifric_platform.frontendPort }}
        env:
        - name: NEXT_PUBLIC_IFRIC_PLATFORM_BACKEND_URL
          value: https://dev-platform-backend.ifric.org
        - name: CONTEXT
          value: https://industry-fusion.org/base/v0.1/
        - name: NEXT_PUBLIC_IFRIC_REGISTRY_BACKEND_URL
          value: https://dev-registry.ifric.org
        - name: NEXT_PUBLIC_ENVIRONMENT
          value: dev
        - name: NEXT_PUBLIC_IFX_PLATFORM_BACKEND_URL
          value: https://dev-platform-backend.industryfusion-x.org
        - name: NEXT_PUBLIC_JWT_SECRET
          value: {{ .Values.ifric_platform.jwtSecret }}
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
