---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: factory50-application-service-prod
  name: factory50-application-service-prod
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.factory50_prod.backendPort }}
    targetPort: {{ .Values.factory50_prod.backendPort }}
    name: factory50-backend
    protocol: TCP
  - port: {{ .Values.factory50_prod.frontendPort }}
    targetPort: {{ .Values.factory50_prod.frontendPort }}
    name: factory50-frontend
    protocol: TCP
  type: LoadBalancer
  selector:
    app: factory50-application-service-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: factory50-application-service-prod
  name: factory50-application-service-prod
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factory50-application-service-prod
  template:
    metadata:
      labels:
        app: factory50-application-service-prod
    spec:
      containers:
      - name: factory50-backend
        image: {{ .Values.mainRepo }}/factory50-backend:{{ .Values.mainVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.factory50_prod.backendPort }}
        env:
        - name: GATEWAY_BASE_URL
          value: https://api.github.com/repos/IndustryFusion/prod-gw-configs/contents
        - name: GATEWAY_TOKEN
          value: {{ .Values.factory50_prod.gatewayToken }}
        - name: GITHUB_BASE_URL
          value: https://api.github.com/repos/IndustryFusion/templates/contents/new-model
        - name: GITHUB_TOKEN
          value: {{ .Values.factory50_prod.githubToken }}
        - name: API_URL
          value: https://platform.industry-fusion.com/auth/realms/iff/protocol/openid-connect/token
        - name: CLIENT_ID
          value: scorpio
        - name: SCORPIO_URL
          value: https://platform.industry-fusion.com/scorpio/ngsi-ld/v1/entities
        - name: S3_URL
          value: s3-eu-central-1.ionoscloud.com
        - name: S3_ACCESS_KEY
          value: {{ .Values.factory50_prod.s3AccessKey }}
        - name: S3_SECRET_KEY
          value: {{ .Values.factory50_prod.s3SecretKey }}
        - name: S3_BUCKET
          value: iff-prod
        - name: ALERTA_URL
          value: https://platform.industry-fusion.com/alerta/api
        - name: ALERTA_KEY
          value: {{ .Values.factory50_prod.alertaKey }}
        - name: TIMESCALE_URL
          value: https://platform.industry-fusion.com/pgrest
        - name: MONGO_URL
          value: {{ .Values.factory50_prod.mongoUrl }}
        - name: CORS_ORIGIN
          value: https://prod-factory.industry-fusion.com
        - name: REDIS_SERVER
          value: "212.132.115.235"
        - name: REDIS_PORT
          value: "6379"
        - name: TEMPLATE_SANDBOX_BACKEND_URL
          value: https://sandbox-backend.industry-fusion.com
        - name: CONTEXT
          value: https://industryfusion.github.io/contexts/tutorial/v0.1-dev/context.jsonld
        - name: JWT_SECRET_KEY
          value: {{ .Values.factory50_prod.jwtSecretKey }}
        - name: IFRIC_REGISTRY_BACKEND_URL
          value: {{ .Values.factory50_prod.registryUrl }}
        - name: IFX_PLATFORM_BACKEND_URL
          value: {{ .Values.factory50_prod.ifxPlatformBackendUrl }}
        - name: ICID_SERVICE_BACKEND_URL
          value: {{ .Values.factory50_prod.icidOrigin }}
        - name: USERNAME
          value: factory_admin@industry-fusion.com
        - name: PASSWORD
          value: "@zN8k51@ORJg"
        
      - name: factory50-frontend
        image: {{ .Values.mainRepo }}/factory50-frontend:{{ .Values.mainVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.factory50_prod.frontendPort }}
        env:
        - name: NEXT_PUBLIC_BACKEND_API_URL
          value: https://prod-factory-backend.industry-fusion.com
        - name: NEXT_PUBLIC_IFRIC_REGISTRY_BACKEND_URL
          value: {{ .Values.factory50_prod.registryUrl }}
        - name: NEXT_PUBLIC_IFX_SUITE_FRONTEND_URL
          value: {{ .Values.factory50_prod.ifxSuiteFrontendUrl }}
        - name: NEXT_PUBLIC_TEMPLATE_SANDBOX_BACKEND_URL
          value: {{ .Values.factory50_prod.sandboxBackendUrl }}
        - name: NEXT_PUBLIC_IFX_PLATFORM_BACKEND_URL
          value: {{ .Values.factory50_prod.ifxPlatformBackendUrl }}
        - name: NEXT_PUBLIC_JWT_SECRET
          value: {{ .Values.factory50_prod.jwtSecret }}
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
