apiVersion: batch/v1
kind: Job
metadata:
  name: init-script-job
  namespace: iff
spec:
  template:
    spec:
      containers:
      - name: init-script
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c", "/scripts/script.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: init-script-configmap
          defaultMode: 0777
      restartPolicy: Never
  backoffLimit: 1