controller:
  image: ibn40/iff-onboarding-controller:v0.1.0
  factoryMongoDbUrl: bW9uZ29kYjovL2ZhY3RvcnltYW5hZ2VyLXVzZXI6ZmZnZ2hobm50dEA4NS4yMTUuNDUuMTYyOjMxMTg5L2ZhY3Rvcnk/ZGlyZWN0Y29ubmVjdGlvbj10cnVlJnJldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhdXRoU291cmNlPWFkbWlu
  factoryMongoDbName: factory
  deviceIfricId: urn:ifric:ifx-eur-nld-ast-567ca6bf-072d-56d9-adff-7529a09242ae