mqtt:
  configuration:
    enabled: true
    name: akri-mqtt
    capacity: 1
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      mqttBrokerUri: "mqtt://192.168.49.26:1883"
      topics:
        - "shellypro3em-08d1f912f61c/events/rpc"
        - "shellypro3em-34987a45fe34/events/rpc"
        - "shellypro3em-34987a466638/events/rpc"
        - "shellypro3em-fcb467058c54/events/rpc"
      timeoutSeconds: 1000


opcua:
  configuration:
    enabled: true
    name: akri-opcua
    capacity: 1
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      discoveryUrls:
        - "opc.tcp://192.168.49.157:48030"

      applicationNames:
        action: Exclude
        items: []

crds:
  group: akri.sh
  version: v0