opcua:
  configuration:
    enabled: true
    name: akri-opcua
    capacity: 1
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      discoveryUrls:
        - "opc.tcp://192.168.2.183:4840"
        - "opc.tcp://192.168.2.183:54845"

      applicationNames:
        action: Include
        items: 
         - "NodeRED-Compact"

crds:
  group: akri.sh
  version: v0