opcua:
  configuration:
    enabled: true
    name: akri-opcua
    capacity: 1
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      discoveryUrls:
        - "opc.tcp://192.168.49.193:62548"

      applicationNames:
        action: Exclude
        items: []

crds:
  group: akri.sh
  version: v0