mqtt:
  configuration:
    enabled: true
    name: akri-mqtt
    capacity: 1
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      mqttBrokerUri: "mqtt://212.227.245.168:1883"
      topics:
        - "airtracker-74145/relay1"
      timeoutSeconds: 5

crds:
  group: akri.sh
  version: v0

controller:
  image: ibn40/iff-akri-controller:v0.0.2
  factoryMongoDbUrl: ""
  factoryMongoDbName: "factoryDB"

namespace: devices