mqtt:
  configuration:
    enabled: true
    name: akri-mqtt
    capacity: 1
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      mqttBrokerUri: "mqtt://192.168.46.135:1883"
      topics:
        - "airtracker-39B58/relay1"
      timeoutSeconds: 5

crds:
  group: akri.sh
  version: v0

controller:
  image: ibn40/iff-akri-controller:v0.0.2
  factoryMongoDbUrl: "mongodb://my-user:ibmistura123@212.132.105.236:31183/admin?directconnection=true&retryWrites=true&w=majority"
  factoryMongoDbName: "admin"

namespace: devices