opcua:
  configuration:
    enabled: true
    name: akri-opcua
    capacity: 1
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      discoveryUrls:
        - "opc.tcp://192.168.49.196:62548"

      applicationNames:
        action: Include
        items: 
         - "Microstep OPC UA Server"
crds:
  group: akri.sh
  version: v0