mqtt:
  configuration:
    enabled: true
    name: akri-mqtt
    capacity: 1
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      mqttBrokerUri: "mqtt://192.168.49.26:1883"
      topics:
        - "kjellberg/plasma/Q-Series/Q-3000/system/status/qunit/json"
      timeoutSeconds: 1000

crds:
  group: akri.sh
  version: v0