opcua:
  configuration:
    enabled: true
    name: akri-opcua
    capacity: 1
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      discoveryUrls:
        - "opc.tcp://192.168.49.151:4840"
        
      applicationNames:
        action: Include
        items: ["SIMATIC.S7-1200.OPC-UA.Application:PLC_1"]

crds:
  group: akri.sh
  version: v0