apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-teka-airtracker-1
  labels:
    app: mqtt-teka-airtracker-1-oisp-sensor
spec:
  selector:
    matchLabels:
      app: mqtt-teka-airtracker-1-oisp-sensor
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mqtt-teka-airtracker-1-oisp-sensor
    spec:
      serviceAccountName: kopfexample-account
      restartPolicy: Always
      containers:
        - name: busybox
          image: docker.io/busybox:latest
          imagePullPolicy: Always
          command: ["sleep"]
          args: ["100000000"]
        - name: fusionmqttdataservice
          env:
            - name: BROKER_URL
              value: "192.168.49.26"
            - name: BROKER_PORT
              value: "1883"
            - name: OISP_URL
              value: "127.0.0.1"
            - name: OISP_PORT
              value: "7070"
            - name: SLEEP
              value: "1"
            - name: OISP_API_ROOT
              value: https://development.industry-fusion.com/oisp/v1/api
            - name: USERNAME
              value: factory_admin@industry-fusion.com
            - name: OISP_DEVICE_ID
              value: "urn:ngsi-ld:assetv5:2:56"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: oisp-password-secret
          image: docker.io/ibn40/fusionmqttdataservice:essen-fair-2
          imagePullPolicy: Always
          volumeMounts:
            - name: dataservice-machine-config
              mountPath: /resources/config.json
              subPath: config.json
        - name: oisp-iot-agent
          env:
            - name: OISP_DEVICE_ID
              value: "urn:ngsi-ld:assetv5:2:56"
            - name: OISP_DEVICE_NAME
              value: "urn:ngsi-ld:assetv5:2:56"
            - name: OISP_GATEWAY_ID
              value: "urn:ngsi-ld:assetv5:2:56"
            - name: OISP_DEVICE_ACTIVATION_CODE
              valueFrom:
                secretKeyRef:
                  key: activation-code
                  name: mqtt-teka-airtracker-1-global-devices-secret
          volumeMounts:
            - name: oisp-devices-config-volume
              mountPath: /volume/config
          securityContext:
            privileged: true
            capabilities:
              drop:
                - all
          image: docker.io/ibn40/oisp-iot-agent:v2.4.2
          imagePullPolicy: Always
          ports:
            - containerPort: 41234
              hostPort: 41234
            - containerPort: 7070
              hostPort: 7070
        - name: oisp-token-operator
          image: ibn40/oisp-token-operator:latest
          imagePullPolicy: Always
          env:
            - name: OISP_API_ROOT
              value: https://development.industry-fusion.com/oisp/v1/api
            - name: USERNAME
              value: factory_admin@industry-fusion.com
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: oisp-password-secret
          securityContext:
            privileged: true
      volumes:
        - name: oisp-devices-config-volume
          configMap:
            name: mqtt-teka-airtracker-1-global-devices-config
            items:
              - key: config.json
                path: config.json
        - name: dataservice-machine-config
          configMap:
            name: mqtt-teka-airtracker-1-app-config
            items:
            - key: config.json
              path: config.json
      imagePullSecrets:
        - name: regcred
      # nodeSelector:
      #   kubernetes.io/hostname: m-3384eee4-d96c-49c0-8ecb-3feaa267213a
