resources:
- deployment.yaml
- mqtt-kjb-power-1-global-devices-config.yaml
- mqtt-kjb-power-1-global-devices-secret.yaml
- mqtt-kjb-power-1-app-config.yaml
- oisp-token-operator-secret.yaml
- oisp-token-operator-role-binding.yaml