apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-airtracker-3-pvc-device-data
  namespace: oisp-devices-dev2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-path
  resources:
    requests:
      storage: 1Mi
