apiVersion: v1
data:
  config.json: |
    {
      "fusionmqttdataservice": {
          "specification": [
              {
                  "topic": "kjellberg/plasma/Q-Series/Q-3000/system/status/qunit/json",
                  "key": ["DEVICE_STATUS"],
                  "parameter": ["machine-state"]
              },
              {
                  "topic": "kjellberg/plasma/Q-Series/Q-3000/consumption/power/json",
                  "key": ["POWER_SUPPLY"],
                  "parameter": ["electric-power"]
              },
              {
                  "topic": "kjellberg/plasma/Q-Series/Q-3000/parameter/actual/json",
                  "key": ["CUTTING_CURRENT", "CUTTING_VOLTAGE"],
                  "parameter": ["current-strength-l1", "supply-voltage-l1"]
              },
              {
                  "topic": "kjellberg/plasma/Q-Series/Q-3000/parameter/actual",
                  "key": ["PG1"],
                  "parameter": ["input-pressure"]
              },
              {
                  "topic": "kjellberg/plasma/Q-Series/Q-3000/parameter/reference",
                  "key": ["PG1"],
                  "parameter": ["static-input-pressure"]
              }
          ]
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mqtt-kjellberg-q3000-1-app-config
