apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-kjb-power-1-pvc-device-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-path
  resources:
    requests:
      storage: 1Mi
