apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-kjb-power-1-pv-device-data
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/devuser"