apiVersion: v1
data:
  device.json: |
    {
        "device_id": "urn:ngsi-ld:asset:2:101",
        "gateway_id": "urn:ngsi-ld:asset:2:101",
        "realm_id": "iff",
        "keycloak_url": "https://development.industry-fusion.com/auth/realms"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mqtt-teka-airtracker-2-data-config
