---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: oisp-devices
  name: kopfexample-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kopfexample-role
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [""]
    resources: ["pods","services","namespaces","deployments","jobs"]
    verbs: ["list", "watch", "patch", "get", "create", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kopfexample-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kopfexample-role
subjects:
  - kind: ServiceAccount
    name: kopfexample-account
    namespace: oisp-devices