apiVersion: v1
data:
  config.json: |
   {
      "fusionopcuadataservice": {
          "specification": [
              {
                  "node_id": "ns=4",
                  "identifier": "i=39",
                  "parameter": "filter-v0.1-filter-runtime-machine-state"
              },
              {
                  "node_id": "ns=4",
                  "identifier": "i=40",
                  "parameter": "base-objects-v0.1-power-supply-runtime-electric-power"
              },
              {
                  "node_id": "ns=4",
                  "identifier": "i=24",
                  "parameter": "filter-v0.1-filter-runtime-operating-hours"
              }
          ]
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opc-teka-aircube-filter-1-app-config
