apiVersion: v1
kind: PersistentVolume
metadata:
  name: opc-mcc-plasma-1-pv-device-data
  namespace: oisp-devices
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/devuser"