apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opc-mcc-plasma-1-pvc-device-data
  namespace: oisp-devices
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-path
  resources:
    requests:
      storage: 1Mi
