apiVersion: v1
data:
  sensorSpecs.json: "[\n    {\n        \"agents\": [\n\t    {\n\t\t\"port\": 41234,\n\t\t\"host\":
    \"127.0.0.1\"\n\t    }],\n\t\"name\": \"tempSensor\",\n\t\"componentName\": \"temp\",\n\t\"componentType\":
    \"Temperature.v1.0\",\n\t\"type\": \"number\",\n\t\"sigma\": 0.1,\n\t\"startValue\":
    20\n    },\n    {\n        \"agents\": [\n\t    {\n\t\t\"port\": 41234,\n\t\t\"host\":
    \"127.0.0.1\"\n\t    }],\n\t\"name\": \"humSensor\",\n\t\"componentName\": \"humidity\",\n\t\"componentType\":
    \"Humidity.v1.0\",\n\t\"type\": \"number\",\n\t\"sigma\": 0.5,\n\t\"startValue\":
    50\n    },\n    {\n        \"agents\": [\n\t    {\n\t\t\"port\": 41234,\n\t\t\"host\":
    \"127.0.0.1\"\n\t    }],\n\t\"name\": \"machineSensor\",\n\t\"componentName\":
    \"machinedata\",\n\t\"componentType\": \"Machinedata.v1.1\",\n\t\"type\": \"string\",\n\t\"sigma\":
    0.5,\n\t\"startValue\": \"A\"\n    }\n]\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: testsensor-2-testsensor-config
  namespace: oisp-devices-dev2
