apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ifric-registry-application-service
  name: ifric-registry-application-service
  namespace: {{ .Values.ifric_registry.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifric-registry-application-service
  template:
    metadata:
      labels:
        app: ifric-registry-application-service
    spec:
      containers:
      - name: ifric-registry-backend
        image: {{ .Values.mainRepo }}/ifric-registry-backend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ifric_registry.backendPort }}
        env:
        - name: GITHUB_BASE_URL
          value: https://api.github.com/repos/IndustryFusion/templates/contents/new-model
        - name: GITHUB_TOKEN
          value: {{ .Values.ifric_registry.githubToken }}
        - name: MONGO_URL
          value: {{ .Values.ifric_registry.mongoUrl }}
        - name: CORS_ORIGIN
          value: https://dev-registry.ifric.org
        - name: ICID_SERVICE_BACKEND_URL
          value: https://dev-icid-service.ifric.org
        - name: IFRIC_PLATFORM_FRONTEND_URL
          value: https://dev-platform.ifric.org
        - name: IFRIC_PLATFORM_BACKEND_URL
          value: https://dev-platform-backend.ifric.org
        - name: IFRIC_DIGITAL_PASSPORT_BACKEND_URL
          value: https://dev-passport-backend.ifric.org
        - name: IFRIC_DIGITAL_PASSPORT_FRONTEND_URL
          value: https://dev-passport.ifric.org
        - name: EMAIL_URL
          value: {{ .Values.ifric_registry.email_url }}
        - name: CLIENT_ID
          value: {{ .Values.ifric_registry.client_id }}
        - name: CLIENT_SECRET
          value: {{ .Values.ifric_registry.client_secret }}
        - name: TENANT_ID
          value: {{ .Values.ifric_registry.tenant_id }}
        - name: COMPANY_DEFAULT_CODE
          value: {{ .Values.ifric_registry.company_default_code }}
        - name: IFRIC_WEBSITE
          value: https://www.ifric.org/
        - name: IFX_PLATFORM_FRONTEND_URL
          value: https://dev-platform.industryfusion-x.org
        - name: IFX_PLATFORM_BACKEND_URL
          value: https://dev-platform-backend.industryfusion-x.org
        - name: IFX_SUITE_FRONTEND_URL
          value: {{ .Values.ifric_registry.ifxSuiteFrontendUrl }}
        - name: IFX_SUITE_BACKEND_URL
          value: {{ .Values.ifric_registry.ifxSuiteBackendUrl }}
        - name: FLEET_MANAGER_BACKEND_URL
          value: https://dev-fleet-backend.industry-fusion.com
        - name: FLEET_MANAGER_FRONTEND_URL
          value: https://dev-fleet.industry-fusion.com
        - name: FACTORY_MANAGER_FRONTEND_URL
          value: https://dev-factory.industry-fusion.com
        - name: FACTORY_MANAGER_BACKEND_URL
          value: https://dev-factory-backend.industry-fusion.com

        # volumeMounts:
        # - name: nginx-config
        #   mountPath: /etc/nginx/conf.d/default.conf
        #   subPath: default.conf
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
      # volumes:
      # - name: nginx-config
      #   configMap:
      #     name: if50-nginx
      #     items:
      #     - key: config
      #       path: default.conf
