apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  containers:
    - name: zookeeper
      image: zookeeper
      ports:
        - containerPort: 2181

---

apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  containers:
    - name: kafka
      image: bitnami/kafka:3.5.1-debian-11-r6
      ports:
        - containerPort: 9092
      env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_LOG_RETENTION_MS
          value: "10000"
        - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
          value: "5000"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock

---

apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgis
      image: postgis/postgis
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: ngb
        - name: POSTGRES_PASSWORD
          value: ngb
        - name: POSTGRES_DB
          value: ngb

---

apiVersion: v1
kind: Pod
metadata:
  name: scorpio
  labels:
    app: scorpio
spec:
  containers:
    - name: scorpio
      image: scorpiobroker/all-in-one-runner:java-kafka-latest
      ports:
        - containerPort: 9090
      env:
        - name: DBHOST
          value: postgres
        - name: BUSHOST
          value: kafka

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka

---

apiVersion: v1
kind: Service
metadata:
  name: scorpio
spec:
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer
  selector:
    app: scorpio

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres