crds:
  group: akri.sh
  version: v0

opcua:
  configuration:
    # enabled defines whether to load an OPC UA configuration
    enabled: true
    # name is the Kubernetes resource name that will be created for this
    # OPC UA configuration
    name: akri-opcua
    # brokerProperties is a map of properties that will be passed to any instances
    # created as a result of applying this OPC UA configuration
    brokerProperties: {}
    capacity: 1
    brokerPod:
      image:
        # repository is the OPC UA broker container reference
        repository:
        # tag is the OPC UA broker image tag
        tag: latest
        # pullPolicy is the OPC UA broker pull policy
        pullPolicy: ""
      resources:
        # memoryRequest defines the minimum amount of RAM that must be available to this Pod
        # for it to be scheduled by the Kubernetes Scheduler
        memoryRequest: 76Mi
        # cpuRequest defines the minimum amount of CPU that must be available to this Pod
        # for it to be scheduled by the Kubernetes Scheduler
        cpuRequest: 9m
        # memoryLimit defines the maximum amount of RAM this Pod can consume.
        memoryLimit: 200Mi
        # cpuLimit defines the maximum amount of CPU this Pod can consume.
        cpuLimit: 30m
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      discoveryUrls:
      - "opc.tcp://192.168.49.195:62548/"
      # applicationNames is a filter applied to the discovered OPC UA servers to either exclusively
      # include or exclude servers with application names in the applicationNames list.
      applicationNames:
        action: Exclude
        items: []
    # mountCertificates determines whether to mount into the broker pods k8s Secrets 
    # containing OPC UA client credentials for connecting to OPC UA severs with the 
    # same signing certificate authority.
    # If set to false, the brokers will attempt to make an insecure connection with the servers.
    mountCertificates: false
    # capacity is the capacity for any instances created as a result of
    # applying this OPC UA configuration