crds:
  group: akri.sh
  version: v0

opcua:
  configuration:
    # enabled defines whether to load an OPC UA configuration
    enabled: true
    # name is the Kubernetes resource name that will be created for this
    # OPC UA configuration
    name: akri-opcua
    # brokerProperties is a map of properties that will be passed to any instances
    # created as a result of applying this OPC UA configuration
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      discoveryUrls:
      - "opc.tcp://192.168.49.195:62548/"
      # applicationNames is a filter applied to the discovered OPC UA servers to either exclusively
      # include or exclude servers with application names in the applicationNames list.
      applicationNames:
        action: Exclude
        items: []