apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mongo-ingress
  namespace: iff
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`*`)
      services:
        - name: mongodb
          port: 27017