apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mongo-ingress
  namespace: {namespace}
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {release_name}
          port: 27017