apiVersion: v1
kind: ConfigMap
metadata:
  name: if50-nginx
data:
  config: |
    server {
      listen 3000;
      listen 4000;
      root /usr/share/nginx/html;
      index index.html;
      location / {
        try_files $uri $uri/;
      }
      gzip on;
    }