apiVersion: v1
kind: ConfigMap
metadata:
  name: if50-nginx
data:
  config: |
    server {
      location / {
        try_files $uri $uri/;
      }

      location /if50 {
        proxy_pass http://localhost:3000;  # Assuming your Next.js app is running on port 3000
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }

      location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|ttf)$ {
        root /app/.next;
        expires 30d;
        access_log off;
        add_header Cache-Control "public, max-age=2592000";
      }
    }