apiVersion: v1
kind: ConfigMap
metadata:
  name: if50-nginx
data:
  config: |
    server {
      location / {
        try_files $uri $uri/;
      }

      location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|ttf)$ {
        root /app/.next;
        expires 30d;
        access_log off;
        add_header Cache-Control "public, max-age=2592000";
      }
    }