apiVersion: v1
kind: ConfigMap
metadata:
  name: if50-nginx
data:
  config: |
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=STATIC:10m inactive=7d use_temp_path=off;
    server {
        listen 80 default_server;

        server_name _;

        server_tokens off;

        gzip on;
        gzip_proxied any;
        gzip_comp_level 4;
        gzip_types text/css application/javascript image/svg+xml;

        location /_next/static {
          proxy_cache STATIC;
          proxy_pass http://localhost:3000;
        }

        location /static {
          proxy_cache STATIC;
          proxy_ignore_headers Cache-Control;
          proxy_cache_valid 60m;
          proxy_pass http://localhost:3000;
        }

        location /if50 {
          proxy_pass http://localhost:3000;
        }
    }