apiVersion: v2
name: backend
description: XANA backend API (NestJS)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - ai
  - xana
  - backend
home: ""
maintainers:
  - name: xana-team
