apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ifx-suite-application-service
  name: ifx-suite-application-service
  namespace: {{ .Values.ifx_suite.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifx-suite-application-service
  template:
    metadata:
      labels:
        app: ifx-suite-application-service
    spec:
      containers:
      - name: ifx-suite-backend
        image: {{ .Values.mainRepo }}/ifx-suite-backend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ifx_suite.backendPort }}
        envFrom:
          - secretRef:
              name: vault-secrets
      - name: ifx-suite-frontend
        image: {{ .Values.mainRepo }}/ifx-suite-frontend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ifx_suite.frontendPort }}
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
