---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ifx-suite-application-service
  name: ifx-suite-application-service
  namespace: ifx-suite
spec:
  ports:
  - name: ifx-suite-backend
    port: 4009
    protocol: TCP
    targetPort: 4009
  - name: ifx-suite-frontend
    port: 3009
    protocol: TCP
    targetPort: 3009
  selector:
    app: ifx-suite-application-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
