apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.release_name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        volumeMounts:
        - name: redis-data
          mountPath: /data
        command: ["redis-server"]
        args: ["--maxclients", "{{ .Values.config.maxclients }}"]
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ .Values.release_name }}-pvc