apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.release_name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}