apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-services-deployments-ingresses
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "update", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "update", "patch"]

