apiVersion: v1
data:
  config.json: |
    {
            "data_directory": "./data",
            "listeners": {
                    "rest_port": 8000,
                    "udp_port": 41234,
                    "tcp_port": 7070
            },
            "receivers": {
                    "udp_port": 41235,
                    "udp_address": "0.0.0.0"
            },
            "logger": {
                    "level": "debug",
                    "path": "/tmp/",
                    "max_size": 134217728
            },
            "default_connector": "rest+ws",
            "connector": {
                    "rest": {
                            "host": "development.industry-fusion.com",
                            "port": 443,
                            "protocol": "https",
                            "strictSSL": false,
                            "timeout": 30000,
                            "proxy": {
                                    "host": false,
                                    "port": false
                            }
                    },
                    "ws": {
                            "host": "ws.development.industry-fusion.com",
                            "port": 443,
                            "minRetryTime": 2500,
                            "maxRetryTime": 600000,
                            "testTimeout": 40000,
                            "pingPongIntervalMs": 30000,
                            "enablePingPong": true,
                            "secure": true,
                            "proxy": {
                                    "host": false,
                                    "port": false
                            }
                    },
                    "mqtt": {
                            "host": "development.industry-fusion.com",
                            "port": 8883,
                            "qos": 1,
                            "retain": false,
                            "secure": true,
                            "strictSSL": true,
                            "retries": 5
                    }
            }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mqtt-airtracker-2-global-devices-config
  namespace: oisp-devices-dev2
