apiVersion: apps/v1
kind: Deployment
metadata:
  name: oisp-operator-1
  labels:
    app: oisp-operator-1
spec:
  selector:
    matchLabels:
      app: oisp-operator-1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oisp-operator-1
    spec:
      serviceAccountName: kopfexample-account
      restartPolicy: Always
      containers:
      - name: oisp-token-operator
        image: ibn40/oisp-token-operator:latest
        imagePullPolicy: Always
        env:
          - name: OISP_API_ROOT
            value: https://development.industry-fusion.com/oisp/v1/api
          - name: USERNAME
            value: factory_admin@industry-fusion.com
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: oisp-password-secret
        securityContext:
          privileged: true
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kopfexample-account
  namespace: oisp-devices

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kopfexample-role
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kopfexample-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopfexample-role
subjects:
  - kind: ServiceAccount
    name: kopfexample-account
    namespace: oisp-devices

---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8vdjEvIjp7InVzZXJuYW1lIjoiZnVzaW9ub3duZXIiLCJwYXNzd29yZCI6IjVmMjk1YTVmM2JlODQ0NDY2ZWUwZTBhMDU2NWFjZjc1IiwiZW1haWwiOiJmdXNpb25vd25lckBpbmR1c3RyeS1mdXNpb24uY29tIiwiYXV0aCI6IlpuVnphVzl1YjNkdVpYSTZOV1l5T1RWaE5XWXpZbVU0TkRRME5qWmxaVEJsTUdFd05UWTFZV05tTnpVPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: oisp-devices
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
stringData:
  password: "@zN8k51@ORJg"
kind: Secret
metadata:
  creationTimestamp: null
  name: oisp-password-secret
  namespace: oisp-devices

---