apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-opcua
spec:
  discoveryHandler:
    name: opcua
    discoveryDetails: |
      opcuaDiscoveryMethod:
        standard:
          discoveryUrls:
          - "opc.tcp://192.168.49.193:62548"

  brokerSpec:
    brokerPodSpec:
      serviceAccountName: kopfexample-account
      restartPolicy: Always
      initContainers:
      - name: oisp-token-operator
        image: ibn40/oisp-token-operator:latest
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "sleep 5; done;" ]
        env:
          - name: OISP_API_ROOT
            value: https://development.industry-fusion.com/oisp/v1/api
          - name: USERNAME
            value: factory_admin@industry-fusion.com
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: oisp-password-secret
        securityContext:
          privileged: true
      containers:
      - name: busybox
        image: docker.io/busybox:latest
        imagePullPolicy: Always
        command: ["sleep"]
        args: ["100000000"]
      - name: fusionopcuadataservice
        env:
          - name: OPC_URL
            value: "opc.tcp://192.168.49.193"
          - name: OPC_PORT
            value: "62548"
          - name: OISP_URL
            value: "127.0.0.1"
          - name: OISP_PORT
            value: "7070"
          - name: OISP_API_ROOT
            value: https://development.industry-fusion.com/oisp/v1/api
          - name: USERNAME
            value: factory_admin@industry-fusion.com
          - name: OISP_DEVICE_ID
            value: "urn:ngsi-ld:assetv5:2:55"
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: oisp-password-secret
        image: docker.io/ibn40/fusionopcuadataservice:essen-fair-2
        imagePullPolicy: Always
        volumeMounts:
          - name: dataservice-machine-config
            mountPath: /resources/config.json
            subPath: config.json
      - name: oisp-iot-agent
        env:
          - name: OISP_DEVICE_ID
            value: "urn:ngsi-ld:assetv5:2:55"
          - name: OISP_DEVICE_NAME
            value: "urn:ngsi-ld:assetv5:2:55"
          - name: OISP_GATEWAY_ID
            value: "urn:ngsi-ld:assetv5:2:55"
          - name: OISP_DEVICE_ACTIVATION_CODE
            valueFrom:
              secretKeyRef:
                key: activation-code
                name: opc-ms-watercut-1-global-devices-secret
        volumeMounts:
          - name: oisp-devices-config-volume
            mountPath: /volume/config
        securityContext:
          privileged: true
          capabilities:
            drop: ["ALL"]
        image: docker.io/ibn40/oisp-iot-agent:v2.4.2
        imagePullPolicy: Always
        ports:
          - containerPort: 41234
            hostPort: 41234
          - containerPort: 7070
            hostPort: 7070
      volumes:
        - name: oisp-devices-config-volume
          configMap:
            name: opc-ms-watercut-1-global-devices-config
            items:
              - key: config.json
                path: config.json
        - name: dataservice-machine-config
          configMap:
            name: opc-ms-watercut-1-app-config
            items:
            - key: config.json
              path: config.json
      imagePullSecrets:
        - name: regcred
      # nodeSelector:
      #   kubernetes.io/hostname: m-3a07708c-8356-460a-81d4-0e62619027bf
  brokerProperties: {}
  capacity: 1

---

apiVersion: v1
data:
  config.json: |
    {
       "fusionopcuadataservice": {
           "specification": [
               {
                   "node_id": "ns=2",
                   "identifier": "s=1:MergedRootGroupNode/MsncCoreRootNode/ActualStateOfCuttingMachine/ActualState?msnc.aSpd",
                   "parameter": "laser-cutter-v0.1-laser-cutter-runtime-cutter-head-speed"
               },
               {
                 "node_id": "ns=2",
                 "identifier": "s=1:MergedRootGroupNode/MsncCoreRootNode/ActualStateOfCuttingMachine/ActualState?msnc.mMov",
                 "parameter": "laser-cutter-v0.1-laser-cutter-runtime-machine-state"
               },
               {
                   "node_id": "ns=2",
                   "identifier": "s=1:MergedRootGroupNode/MsncCoreRootNode/ActualStateOfCuttingMachine/ActualPosition?msnc.mAxX",
                   "parameter": "laser-cutter-v0.1-laser-cutter-runtime-machine-position-x"
               },
               {
                 "node_id": "ns=2",
                 "identifier": "s=1:MergedRootGroupNode/MsncCoreRootNode/ActualStateOfCuttingMachine/ActualPosition?msnc.mAxY",
                 "parameter": "laser-cutter-v0.1-laser-cutter-runtime-machine-position-y"
               },
               {
                 "node_id": "ns=2",
                 "identifier": "s=1:MergedRootGroupNode/MsncCoreRootNode/ActualStateOfCuttingMachine/ActualPosition?msnc.mAxZ",
                 "parameter": "laser-cutter-v0.1-laser-cutter-runtime-machine-position-z"
               }
           ]
       }
     }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opc-ms-watercut-1-app-config

---

apiVersion: v1
data:
  config.json: |
    {
                "data_directory": "./data",
                "listeners": {
                        "rest_port": 8000,
                        "udp_port": 41234,
                        "tcp_port": 7070
                },
                "receivers": {
                        "udp_port": 41235,
                        "udp_address": "127.0.0.1"
                },
                "logger": {
                        "level": "info",
                        "path": "/tmp/",
                        "max_size": 134217728
                },
                "connector": {
                        "rest": {
                                "host": "development.industry-fusion.com",
                                "port": 443,
                                "protocol": "https",
                                "strictSSL": false,
                                "timeout": 30000,
                                "proxy": {
                                        "host": false,
                                        "port": false
                                }
                        },
                        "mqtt": {
                                "host": "development.industry-fusion.com",
                                "port": 8883,
                                "websockets": false,
                                "qos": 1,
                                "retain": false,
                                "secure": true,
                                "retries": 5,
                                "strictSSL": false,
                                "sparkplugB": true,
                                "version": "spBv1.0"        
                        }
                }
        }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opc-ms-watercut-1-global-devices-config

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kopfexample-account
  namespace: oisp-devices

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kopfexample-role
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kopfexample-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopfexample-role
subjects:
  - kind: ServiceAccount
    name: kopfexample-account
    namespace: oisp-devices

---

apiVersion: v1
stringData:
  activation-code: Bagq8zgU
kind: Secret
metadata:
  creationTimestamp: null
  name: opc-ms-watercut-1-global-devices-secret
  namespace: oisp-devices

---

apiVersion: v1
stringData:
  password: "@zN8k51@ORJg"
kind: Secret
metadata:
  creationTimestamp: null
  name: oisp-password-secret
  namespace: oisp-devices

---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8vdjEvIjp7InVzZXJuYW1lIjoiZnVzaW9ub3duZXIiLCJwYXNzd29yZCI6IjVmMjk1YTVmM2JlODQ0NDY2ZWUwZTBhMDU2NWFjZjc1IiwiZW1haWwiOiJmdXNpb25vd25lckBpbmR1c3RyeS1mdXNpb24uY29tIiwiYXV0aCI6IlpuVnphVzl1YjNkdVpYSTZOV1l5T1RWaE5XWXpZbVU0TkRRME5qWmxaVEJsTUdFd05UWTFZV05tTnpVPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: oisp-devices
type: kubernetes.io/dockerconfigjson

---