environments:
  default:
    values:
    - environment/default.yaml
    - common.gotmpl
    - common.yaml
  production:
    values:
    - environment/production.yaml
    - common.gotmpl
    - common.yaml

releases:
- name: postgres
  labels:
    order: first
    app: postgres
  chart: ./charts/postgres
  namespace: iff
  needs:
  - minio
  values:
  - values.yaml.gotmpl
- name: kafka
  labels:
    order: second
    app: kafka
  chart: ./charts/kafka
  namespace: iff
  needs:
  - postgres
  values:
  - values.yaml.gotmpl
- name: cert-manager
  labels:
    order: first
    app: cert-manager
  chart: ./charts/cert-manager
  namespace: iff
  values:
  - values.yaml.gotmpl
- name: keycloak
  labels:
    order: first
    app: keycloak
  chart: ./charts/keycloak
  namespace: iff
  needs:
  - postgres
  values:
  - values.yaml.gotmpl
- name: alerta
  labels:
    order: third
    app: alerta
  chart: ./charts/alerta
  namespace: iff
  values:
  - values.yaml.gotmpl
  needs:
  - postgres
  - keycloak
- name: scorpio
  labels:
    order: second
    app: scorpio
  chart: ./charts/scorpio
  namespace: iff
  values:
  - values.yaml.gotmpl
  needs:
  - postgres
  - keycloak
  - kafka
- name: flink
  labels:
    app: flink
    order: third
  chart: ./charts/flink
  namespace: iff
  values:
  - values.yaml.gotmpl
  needs:
  - kafka
  - minio
- name: minio
  labels:
    order: first
    app: minio
  chart: ./charts/minio
  namespace: iff
  values:
  - values.yaml.gotmpl
- name: kafka-bridges
  labels:
    app: kafka-bridges
    order: third
  chart: ./charts/kafka-bridges
  namespace: iff
  values:
  - values.yaml.gotmpl
  needs:
  - kafka
  - keycloak
  - alerta
- name: sql-core
  labels:
    app: sql-core
    order: third
  chart: ./charts/sql-core
  namespace: iff
  values:
  - values.yaml.gotmpl
  needs:
  - kafka
  - flink
  - alerta
  - scorpio
  - kafka-bridges
- name: velero
  labels:
    app: velero
  chart: ./charts/velero
  namespace: velero
  values:
  - values.yaml.gotmpl
  needs:
  - iff/minio
- name: redis
  labels:
    app: redis
    order: first
  chart: ./charts/redis
  namespace: iff
  values:
  - values.yaml.gotmpl
- name: emqx
  labels:
    app: emqx
    order: third
  chart: ./charts/emqx
  namespace: iff
  values:
  - values.yaml.gotmpl
  needs:
  - kafka-bridges
- name: pgrest
  labels:
    app: pgrest
    order: second
  chart: ./charts/pgrest
  namespace: iff
  values:
  - values.yaml.gotmpl
  needs:
  - postgres