apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads
  labels:
    {{- include "svc.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass | quote }}
  {{- end }}
