apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passport-creator-application-service
  name: passport-creator-application-service
  namespace: {{ .Values.passport_creator.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passport-creator-application-service
  template:
    metadata:
      labels:
        app: passport-creator-application-service
    spec:
      containers:
      - name: passport-creator-backend
        image: {{ .Values.mainRepo }}/passport-creator-backend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.passport_creator.backendPort }}
        env:
        - name: GITHUB_BASE_URL
          value: https://api.github.com/repos/IndustryFusion/templates/contents/new-temp
        - name: GITHUB_TOKEN
          value: {{ .Values.passport_creator.githubToken }}
        - name: SCORPIO_URL
          value: http://85.215.171.58:9090/ngsi-ld/v1/entities
        - name: S3_URL
          value: s3-eu-central-1.ionoscloud.com
        - name: S3_ACCESS_KEY
          value: {{ .Values.passport_creator.s3AccessKey }}
        - name: S3_SECRET_KEY
          value: {{ .Values.passport_creator.s3SecretKey }}
        - name: S3_BUCKET
          value: iff-dev
        - name: USERNAME
          value: {{ .Values.passport_creator.username }}
        - name: PASSWORD
          value: {{ .Values.passport_creator.password }}
        - name: CORS_ORIGIN
          value: ''
        - name: ICID_ORIGIN
          value: http://87.106.207.10:4010
        - name: ASSETS_DEFAULT_CODE
          value: IFX-EUR-NLD-AST
        - name: USERS_DEFAULT_CODE
          value: IFX-EUR-NLD-USR
        - name: CONTEXT
          value: https://industryfusion.github.io/contexts/tutorial/v0.1-dev/context.jsonld
        - name: MONGO_URL
          value: {{ .Values.passport_creator.mongoUrl }}
      - name: passport-creator-frontend
        image: {{ .Values.mainRepo }}/passport-creator-frontend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.passport_creator.frontendPort }}
        env:
        - name: NEXT_PUBLIC_BACKEND_API_URL
          value: https://dev-dpp-creator-backend.ifric.org
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
