apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ifx-platform-application-service
  name: ifx-platform-application-service
  namespace: {{ .Values.ifx_platform.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifx-platform-application-service
  template:
    metadata:
      labels:
        app: ifx-platform-application-service
    spec:
      containers:
      - name: ifx-platform-backend
        image: {{ .Values.mainRepo }}/ifx-platform-backend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ifx_platform.backendPort }}
        env:
        - name: GITHUB_BASE_URL
          value: https://api.github.com/repos/IndustryFusion/templates/contents/new-temp
        - name: GITHUB_TOKEN
          value: {{ .Values.ifx_platform.githubToken }}
        - name: GITHUB_ERP_URL
          value: https://api.github.com/repos/IndustryFusion/templates/contents/erp-field-maps
        - name: SCORPIO_URL
          value: http://85.215.171.58:9090/ngsi-ld/v1/entities
        - name: S3_URL
          value: s3-eu-central-1.ionoscloud.com
        - name: S3_ACCESS_KEY
          value: {{ .Values.ifx_platform.s3AccessKey }}
        - name: S3_SECRET_KEY
          value: {{ .Values.ifx_platform.s3SecretKey }}
        - name: S3_BUCKET
          value: iff-dev
        - name: USERNAME
          value: {{ .Values.ifx_platform.username }}
        - name: PASSWORD
          value: {{ .Values.ifx_platform.password }}
        - name: ICID_SERVICE_BACKEND_URL
          value: {{ .Values.ifx_platform.icidOrigin }}
        - name: CORS_ORIGIN
          value: {{ .Values.ifx_platform.corsOrigin }}
        - name: ASSETS_DEFAULT_CODE
          value: IFX-EUR-NLD-AST
        - name: USERS_DEFAULT_CODE
          value: IFX-EUR-NLD-USR
        - name: CONTEXT
          value: https://industryfusion.github.io/contexts/tutorial/v0.1-dev/context.jsonld
        - name: MONGO_URL
          value: {{ .Values.ifx_platform.mongoUrl }}
        - name: JIRA_URL
          value: {{ .Values.ifx_platform.jiraUrl }}
        - name: EMAIL_URL
          value: {{ .Values.ifx_platform.emailUrl }}
        - name: CLIENT_ID
          value: {{ .Values.ifx_platform.clientId }}
        - name: CLIENT_SECRET
          value: {{ .Values.ifx_platform.clientSecret }}
        - name: TENANT_ID
          value: {{ .Values.ifx_platform.tenantId }}
        - name: JIRA_TOKEN
          value: {{ .Values.ifx_platform.jiraToken }}
        - name: IFRIC_REGISTRY_BACKEND_URL
          value: {{ .Values.ifx_platform.registryUrl }}
        - name: TEMPLATE_SANDBOX_BACKEND_URL
          value: {{ .Values.ifx_platform.sandboxBackendUrl }}
        - name: IFRIC_PLATFORM_SCORPIO_URL
          value: {{ .Values.ifx_platform.scorpioUrl }}
        - name: IFRIC_PLATFORM_FRONTEND_URL
          value: {{ .Values.ifx_platform.platformFrontendUrl }}
        - name: IFRIC_PLATFORM_BACKEND_URL
          value: {{ .Values.ifx_platform.platformBackendUrl }}
        - name: FACTORY_MANAGER_FRONTEND_URL
          value: {{ .Values.ifx_platform.factoryFrontendUrl }}
        - name: FLEET_FRONTEND_URL
          value: {{ .Values.ifx_platform.fleetFrontendUrl }}
        - name: FLEET_BACKEND_URL
          value: {{ .Values.ifx_platform.fleetBackendUrl }}
        - name: JWT_SECRET
          value: {{ .Values.ifx_platform.jwtSecret }}
      - name: ifx-platform-frontend
        image: {{ .Values.mainRepo }}/ifx-platform-frontend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ifx_platform.frontendPort }}
        env:
        - name: NEXT_PUBLIC_IFRIC_REGISTRY_BACKEND_URL
          value: {{ .Values.ifx_platform.registryUrl }}
        - name: NEXT_PUBLIC_TEMPLATE_SANDBOX_BACKEND_URL
          value: {{ .Values.ifx_platform.sandboxBackendUrl }}
        - name: NEXT_PUBLIC_IFX_BACKEND_URL
          value: {{ .Values.ifx_platform.ifxBackendUrl }}
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
