---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ifx-platform-application-service
  name: ifx-platform-application-service
  namespace: ifx-platform
spec:
  ports:
  - name: ifx-platform-backend
    port: 4008
    protocol: TCP
    targetPort: 4008
  - name: ifx-platform-frontend
    port: 3008
    protocol: TCP
    targetPort: 3008
  selector:
    app: ifx-platform-application-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
