---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ifx-platform-application-service
  name: ifx-platform-application-service
  namespace: ifx-platform
spec:
  ports:
  - port: 3008
    targetPort: 3008
    name: ifx-platform-frontend
    protocol: TCP
  type: LoadBalancer
  selector:
    app: ifx-platform-application-service
