ingressType: traefik

icsdbExternalHostname: icsdb.local
icsdbExternalPath: /ics/ # must end with /
# fleetmanagerExternalHostname: fleetmanager.local
# fleetmanagerBackendExternalPath: /fleetmanager/backend/ # must end with /
# fleetmanagerFrontendExternalPath: /fleetmanager  # must end with /
# if50ExternalHostname: development.industry-fusion.com
# if50BackendExternalPath: /if50/backend/ # must end with /
# if50FrontendExternalPath: /if50 # must end without /

dev:
  factory50ExternalHostname: development.industry-fusion.com
  factory50BackendExternalPath: /factory50/backend/ # must end with /
  factory50FrontendExternalPath: /factory50 # must end without /

  fleet50ExternalHostname: development.industry-fusion.com
  fleet50BackendExternalPath: /fleet50/backend/ # must end with /
  fleet50FrontendExternalPath: /fleet50 # must end without /


prod:
  factory50ExternalHostname: platform.industry-fusion.com
  factory50BackendExternalPath: /factory50/backend/ # must end with /
  factory50FrontendExternalPath: /factory50 # must end without /

  fleet50ExternalHostname: platform.industry-fusion.com
  fleet50BackendExternalPath: /fleet50/backend/ # must end with /
  fleet50FrontendExternalPath: /fleet50 # must end without /



certmanager:
  secret: selfsigned-cert-tls
  issuer: letsencrypt-self

# s3:
#   url: https://s3-eu-central-1.ionoscloud.com
#   accessKey: access-key
#   secretKey: secret-key
#   fleetmanagerBucket: iff-dev

alerta_dev:
  url: https://development.industry-fusion.com/alerta
  accesskey: access-key

alerta_prod:
  url: https://alerta.industry-fusion.com/alerta
  accesskey: access-key

# icid:
#   mongoUrl: ''
#   namespace: ''

# fleet50:
#   githubToken: ''
#   s3AccessKey: ''
#   s3SecretKey: ''
#   username: ''
#   password: ''

# factory50:
#   gatewayToken: ''
#   githubToken: ''
#   s3AccessKey: ''
#   s3SecretKey: ''
#   alertaKey: ''
#   mongoUrl: ''
