apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: passport-viewer-application-service
  name: passport-viewer-application-service
  namespace: {{ .Values.passport_viewer.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passport-viewer-application-service
  template:
    metadata:
      labels:
        app: passport-viewer-application-service
    spec:
      containers:
      - name: passport-viewer-backend
        image: {{ .Values.mainRepo }}/passport-viewer-backend:{{ .Values.mainVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.passport_viewer.backendPort }}
        env:
        - name: GITHUB_BASE_URL
          value: https://api.github.com/repos/IndustryFusion/templates/contents/new-model
        - name: GITHUB_TOKEN
          value: {{ .Values.passport_viewer.githubToken }}
        - name: SCORPIO_URL
          value: https://dev-dataroom.ifric.org/ngsi-ld/v1/entities
        - name: CORS_ORIGIN
          value: https://dev-dpp-viewer.ifric.org
        - name: S3_URL
          value: s3-eu-central-1.ionoscloud.com
        - name: S3_ACCESS_KEY
          value: {{ .Values.passport_viewer.s3AccessKey }}
        - name: S3_SECRET_KEY
          value: {{ .Values.passport_viewer.s3SecretKey }}
        - name: S3_BUCKET
          value: iff-dev
        - name: USERNAME
          value: {{ .Values.passport_viewer.username }}
        - name: PASSWORD
          value: {{ .Values.passport_viewer.password }}
      - name: passport-viewer-frontend
        image: {{ .Values.mainRepo }}/passport-viewer-frontend:{{ .Values.mainVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.passport_viewer.frontendPort }}
        env:
        - name: NEXT_PUBLIC_BACKEND_API_URL
          value: https://dev-dpp-viewer-backend.ifric.org
        # volumeMounts:
        # - name: nginx-config
        #   mountPath: /etc/nginx/conf.d/default.conf
        #   subPath: default.conf
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
      # volumes:
      # - name: nginx-config
      #   configMap:
      #     name: if50-nginx
      #     items:
      #     - key: config
      #       path: default.conf
