---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: factory50-application-service
  name: factory50-application-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.factory50.backendPort }}
    targetPort: {{ .Values.factory50.backendPort }}
    name: factory50-backend
    protocol: TCP
  - port: {{ .Values.factory50.frontendPort }}
    targetPort: {{ .Values.factory50.frontendPort }}
    name: factory50-frontend
    protocol: TCP
  type: LoadBalancer
  selector:
    app: factory50-application-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: factory50-application-service
  name: factory50-application-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factory50-application-service
  template:
    metadata:
      labels:
        app: factory50-application-service
    spec:
      containers:
      - name: factory50-backend
        image: {{ .Values.mainRepo }}/factory50-backend:{{ .Values.mainVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.factory50.backendPort }}
        env:
        - name: GATEWAY_BASE_URL
          value: {{ .Values.factory50.gatewayBaseUrl }}
        - name: GATEWAY_TOKEN
          value: {{ .Values.factory50.gatewayToken }}
        - name: GITHUB_BASE_URL
          value: {{ .Values.factory50.githubBaseUrl }}
        - name: GITHUB_TOKEN
          value: {{ .Values.factory50.githubToken }}
        - name: API_URL
          value: {{ .Values.factory50.apiUrl }}
        - name: CLIENT_ID
          value: scorpio
        - name: CONTEXT
          value: https://industryfusion.github.io/contexts/tutorial/v0.1-dev/context.jsonld
        - name: SCORPIO_URL
          value: {{ .Values.factory50.scorpioUrl }}
        - name: S3_URL
          value: s3-eu-central-1.ionoscloud.com
        - name: S3_ACCESS_KEY
          value: {{ .Values.factory50.s3AccessKey }}
        - name: S3_SECRET_KEY
          value: {{ .Values.factory50.s3SecretKey }}
        - name: JWT_SECRET_KEY
          value: {{ .Values.factory50.jwtSecretKey }}
        - name: S3_BUCKET
          value: iff-dev
        - name: ALERTA_URL
          value: {{ .Values.factory50.alertaUrl }}
        - name: ALERTA_KEY
          value: {{ .Values.factory50.alertaKey }}
        - name: TIMESCALE_URL
          value: {{ .Values.factory50.timescaleUrl }}
        - name: MONGO_URL
          value: {{ .Values.factory50.mongoUrl }}
        - name: IFRIC_REGISTRY_BACKEND_URL
          value: {{ .Values.factory50.registryUrl }}
        - name: TEMPLATE_SANDBOX_BACKEND_URL
          value: {{ .Values.factory50.sandboxBackendUrl }}
        - name: IFX_PLATFORM_BACKEND_URL
          value: {{ .Values.factory50.ifxPlatformBackendUrl }}
        - name: ICID_SERVICE_BACKEND_URL
          value: {{ .Values.factory50.icidOrigin }}
        - name: CORS_ORIGIN
          value: {{ .Values.factory50.corsOrigin }}
        - name: REDIS_SERVER
          value: "212.132.115.232"
        - name: REDIS_PORT
          value: "6379"
      - name: factory50-frontend
        image: {{ .Values.mainRepo }}/factory50-frontend:{{ .Values.mainVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.factory50.frontendPort }}
        env:
        - name: NEXT_PUBLIC_BACKEND_API_URL
          value: {{ .Values.factory50.FactoryBackendUrl }}
        - name: NEXT_PUBLIC_IFRIC_REGISTRY_BACKEND_URL
          value: {{ .Values.factory50.registryUrl }}
        - name: NEXT_PUBLIC_IFX_SUITE_FRONTEND_URL
          value: {{ .Values.factory50.ifxSuiteFrontendUrl }}
        - name: NEXT_PUBLIC_TEMPLATE_SANDBOX_BACKEND_URL
          value: {{ .Values.factory50.sandboxBackendUrl }}
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
