---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: factory50-application-service
  name: factory50-application-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.factory50.backendPort }}
    targetPort: {{ .Values.factory50.backendPort }}
    name: factory50-backend
    protocol: TCP
  - port: {{ .Values.factory50.frontendPort }}
    targetPort: {{ .Values.factory50.frontendPort }}
    name: factory50-frontend
    protocol: TCP
  type: LoadBalancer
  selector:
    app: factory50-application-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: factory50-application-service
  name: factory50-application-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factory50-application-service
  template:
    metadata:
      labels:
        app: factory50-application-service
    spec:
      containers:
      - name: factory50-backend
        image: {{ .Values.mainRepo }}/factory50-backend:{{ .Values.mainVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.factory50.backendPort }}
        env:
        - name: GITHUB_BASE_URL
          value: https://api.github.com/repos/IndustryFusion/templates/contents
        - name: GITHUB_TOKEN
          value: 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
        - name: API_URL
          value: https://development.industry-fusion.com/auth/realms/iff/protocol/openid-connect/token
        - name: CLIENT_ID
          value: scorpio
        - name: SCORPIO_URL
          value: https://development.industry-fusion.com/scorpio/ngsi-ld/v1/entities
        - name: S3_URL
          value: s3-eu-central-1.ionoscloud.com
        - name: S3_ACCESS_KEY
          value: 00a2a60dfb1b2ff13356
        - name: S3_SECRET_KEY
          value: 79SOXZke/2oDZEHOmPVQP1+E182aT3VsE//0klww
        - name: S3_BUCKET
          value: iff-dev
        - name: ALERTA_URL
          value: https://development.industry-fusion.com/alerta/api
        - name: ALERTA_KEY
          value: sN2VXjf0sYQaOeCfUoinz16bnnk0VDYW
        - name: TIMESCALE_URL
          value: https://development.industry-fusion.com/pgrest/entityhistory
        - name: MONGO_URL
          value: mongodb://my-user:ibmistura123@212.132.105.236:31183/admin?directconnection=true&retryWrites=true&w=majority
        - name: CORS_ORIGIN
          value: http://85.215.128.232:3002
      - name: factory50-frontend
        image: {{ .Values.mainRepo }}/factory50-frontend:{{ .Values.mainVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.factory50.frontendPort }}
        env:
        - name: NEXT_PUBLIC_BACKEND_API_URL
          value: http://85.215.128.232:4002
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}