apiVersion: v1
kind: ConfigMap
metadata:
  name: factory50-env
data:
  config: |
    GITHUB_BASE_URL=https://api.github.com/repos/IndustryFusion/templates/contents
    GITHUB_TOKEN=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
    API_URL=https://development.industry-fusion.com/auth/realms/iff/protocol/openid-connect/token
    CLIENT_ID=scorpio
    SCORPIO_URL=https://development.industry-fusion.com/scorpio/ngsi-ld/v1/entities
    S3_URL=s3-eu-central-1.ionoscloud.com
    S3_ACCESS_KEY=00a2a60dfb1b2ff13356
    S3_SECRET_KEY=79SOXZke/2oDZEHOmPVQP1+E182aT3VsE//0klww
    S3_BUCKET=iff-dev
    ALERTA_URL=https://development.industry-fusion.com/alerta/api
    ALERT_KEY=m1PTpd5JaTYwlmp22HhO1676hNhlxmrt
    TIMESCALE_URL=https://development.industry-fusion.com/pgrest/entityhistory
    MONGO_URL=mongodb://my-user:ibmistura123@194.164.195.235:31183/admin?directconnection=true&retryWrites=true&w=majority
    CORS_ORIGIN=http://85.215.128.232:3002