---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: factory50-application-service
  name: factory50-application-service
  namespace: {{ .Values.factory50.namespace }}
spec:
  ports:
  - port: {{ .Values.factory50.backendPort }}
    targetPort: {{ .Values.factory50.backendPort }}
    name: factory50-backend
    protocol: TCP
  - port: {{ .Values.factory50.frontendPort }}
    targetPort: {{ .Values.factory50.frontendPort }}
    name: factory50-frontend
    protocol: TCP
  type: LoadBalancer
  selector:
    app: factory50-application-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: factory50-application-service
  name: factory50-application-service
  namespace: {{ .Values.factory50.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factory50-application-service
  template:
    metadata:
      labels:
        app: factory50-application-service
    spec:
      containers:
      - name: factory50-backend
        image: {{ .Values.mainRepo }}/factory50-backend:{{ .Values.mainVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.factory50.backendPort }}
        envFrom:
          - secretRef:
              name: vault-secrets
      - name: factory50-frontend
        image: {{ .Values.mainRepo }}/factory50-frontend:{{ .Values.mainVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.factory50.frontendPort }}
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
