---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: icsdb-service
  name: icsdb-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.icsdb.port }}
    targetPort: {{ .Values.icsdb.port }}
    protocol: TCP
  selector:
    app: icsdb-service
---
{{- $mongodbsecret := (lookup "v1" "Secret" .Release.Namespace "mongodb-connection") -}}
{{- $icsdbsecret := (lookup "v1" "Secret" .Release.Namespace "icsdb-user") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: icsdb-service
  name: icsdb-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
   matchLabels:
    app: icsdb-service
  replicas: 1
  template:
    metadata:
      labels:
        app: icsdb-service
    spec:
      containers:
      - name: icsdb-service
        image: {{ .Values.mainRepo }}/icsdbservice:{{ .Values.mainVersion }}
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: {{ .Values.icsdb.port }}
           hostPort: {{ .Values.icsdb.port }}
        env:
        {{- if $mongodbsecret }}
        - name: MONGODB_URL
          value: {{ index $mongodbsecret "data" "connectionString.standard" | toString | b64dec }}
        {{- end }}
        {{- if $icsdbsecret }}
        - name: USERNAME
          value: {{ $icsdbsecret.data.username | toString | b64dec }}
        - name: PASSWORD
          value: {{ $icsdbsecret.data.password | toString | b64dec }}
        {{- else }}
        - name: USERNAME
          value: {{ .Values.icsdb.username | toString }}
        - name: PASSWORD
          value: {{ .Values.icsdb.password | toString }}
        {{- end }}
        - name: ICSDB_PORT
          value: "{{ .Values.icsdb.port | toString }}"
        - name: RESOURCE_FOLDER
          value: ../resources/templates
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
