---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: icid-application-service
  name: icid-application-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.icid.backendPort }}
    targetPort: {{ .Values.icid.backendPort }}
    name: icid-backend
    protocol: TCP
  type: LoadBalancer
  selector:
    app: icid-application-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: icid-application-service
  name: icid-application-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icid-application-service
  template:
    metadata:
      labels:
        app: icid-application-service
    spec:
      containers:
      - name: icid-backend
        image: {{ .Values.mainRepo }}/icid-backend:{{ .Values.mainVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.icid.backendPort }}
        env:
        - name: MONGO_URL
          value: {{ .Values.icid.mongoUrl }}
        - name: IFRIC_NAMESPACE
          value: {{ .Values.icid.namespace }}
        - name: FLEET_MANAGER_BACKEND_URL
          value: {{ .Values.icid.fleetBackendUrl }}
        - name: IFRIC_PLATFORM_BACKEND_URL
          value: {{ .Values.icid.platformBackendUrl }}
        - name: IFRIC_REGISTRY_BACKEND_URL
          value: {{ .Values.icid.registryUrl }}
      imagePullSecrets:
      - name: {{ .Values.pullSecretCredentials }}
