{{- if not .Values.cluster.enabled }}
{{- $pvc := .Values.standalone.persistence.persistentVolumeClaim -}}
{{- if and .Values.standalone.persistence.enabled (not $pvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-data-disk
  namespace: {{ .Release.Namespace }}
{{- with .Values.standalone.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    apps: milvus-xana
spec:
  accessModes:
  - {{ $pvc.accessModes | quote }}
  {{- if $pvc.storageClass }}
    {{- if eq "-" $pvc.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $pvc.storageClass }}
    {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ $pvc.size }}
{{- end }}
{{- end }}

{{- $pvc := .Values.log.persistence.persistentVolumeClaim -}}
{{- if and .Values.log.persistence.enabled (not $pvc.existingClaim)}}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-logs-disk
  namespace: {{ .Release.Namespace }}
  labels:
    apps: milvus-xana
spec:
  accessModes:
  - {{ $pvc.accessModes | quote }}
  {{- if $pvc.storageClass }}
    {{- if eq "-" $pvc.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $pvc.storageClass }}
    {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ $pvc.size }}
{{- end }}
