{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: milvus-xana
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    app: milvus-xana
    component: "standalone"
{{- with .Values.serviceAccount.labels }}
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}