{{- if not .Values.cluster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-xana
  namespace: {{ .Release.Namespace }}
  labels:
    app: milvus-xana
    component: standalone

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: milvus-xana
      component: "standalone"
  template:
    metadata:
      labels:
        app: milvus-xana
        component: "standalone"
    spec:
      initContainers:
      {{- if .Values.standalone.heaptrack.enabled }}
      - name: heaptrack
        command:
        - /bin/bash
        - -c
        - "cp -r /opt/heaptrack /milvus/tools"
        image: "{{ .Values.heaptrack.image.repository }}:{{ .Values.heaptrack.image.tag }}"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /milvus/tools
          name: tools
      {{- end }}
      containers:
      - name: standalone
        image: "{{ .Values.image.all.repository }}:{{ .Values.image.all.tag }}"
        imagePullPolicy: IfNotPresent
        args: [ "milvus", "run", "standalone" ]
        ports:
          - name: milvus
            containerPort: 19530
            protocol: TCP
          - name: metrics
            containerPort: 9091
            protocol: TCP
        resources:
          {{- toYaml .Values.standalone.resources | nindent 10 }}
        env:
        {{- if .Values.standalone.heaptrack.enabled }}
        - name: LD_LIBRARY_PATH
          value: /milvus/tools/heaptrack/lib:/milvus/lib:/usr/lib
        {{- end }}
        {{- if .Values.standalone.disk.size.enabled }}
        - name: LOCAL_STORAGE_SIZE
          valueFrom:
            resourceFieldRef:
              divisor: 1Gi
              resource: limits.ephemeral-storage
        {{- end }}
        {{- if .Values.standalone.extraEnv }}
          {{- toYaml .Values.standalone.extraEnv | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: /milvus/tools
          name: tools
        - name: milvus-config
          mountPath: /milvus/configs/default.yaml
          subPath: default.yaml
          readOnly: true
        - name: milvus-config
          mountPath: /milvus/configs/user.yaml
          subPath: user.yaml
          readOnly: true
        - name: milvus-data-disk
          mountPath: {{ .Values.standalone.persistence.mountPath | quote }}
          subPath: {{ .Values.standalone.persistence.persistentVolumeClaim.subPath | default "" }}
        {{- if .Values.standalone.disk.enabled }}
        - mountPath: /var/lib/milvus/data
          name: disk
        {{- end }}

      volumes:
      - emptyDir: {}
        name: tools
      - name: milvus-data-disk
        {{- if .Values.standalone.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.standalone.persistence.persistentVolumeClaim.existingClaim | default (printf "%s" (include "milvus-data-disk" . | trunc 58)) }}
        {{- end }}
      {{- if .Values.standalone.disk.enabled }}
      - name: disk
        emptyDir: {}
      {{- end }}
{{- end }}
