apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.auth.rootUser }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "{{ .Values.auth.rootPassword }}"
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.auth.database }}"
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongodb-pvc