{{- $secret := (lookup "v1" "Secret" .Release.Namespace "keycloak-client-secret-oisp-frontend") -}}
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-client-secret-oisp-frontend
    namespace: {{ .Release.Namespace }}
{{ if $secret }}
data:
    CLIENT_ID: {{ $secret.data.CLIENT_ID }}
    CLIENT_SECRET: {{ $secret.data.CLIENT_SECRET }}
{{ else }}
data:
    CLIENT_ID: {{ .Values.keycloak.oisp.frontend.client | toString | b64enc }}
    CLIENT_SECRET: {{ .Values.keycloak.oisp.frontend.clientSecret | toString | b64enc }}
{{ end }}
type: Opaque