{{- if .Values.opcua.configuration.enabled }}
apiVersion: {{ printf "%s/%s" .Values.crds.group .Values.crds.version }}
kind: Configuration
metadata:
  name: {{ .Values.opcua.configuration.name }}
spec:
  discoveryHandler:
    name: opcua
    discoveryDetails:
      opcuaDiscoveryMethod: 
        standard:
          discoveryUrls: 
          - "opc.tcp://192.168.49.195:62548/"

  brokerSpec:
    brokerPodSpec:
      containers:
      - name: busybox
        image: docker.io/busybox:latest
        imagePullPolicy: Always
        command: ["sleep"]
        args: ["100000000"]
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
      - name: fusionopcuadataservice
        env:
          - name: OPC_URL
            value: "opc.tcp://192.168.49.195"
          - name: OPC_PORT
            value: "62548"
          - name: OISP_URL
            value: "127.0.0.1"
          - name: OISP_PORT
            value: "7070"
          - name: OISP_API_ROOT
            value: https://development.industry-fusion.com/oisp/v1/api
          - name: USERNAME
            value: factory_admin@industry-fusion.com
          - name: OISP_DEVICE_ID
            value: "urn:ngsi-ld:assetv5:2:55"
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: oisp-password-secret
        image: docker.io/ibn40/fusionopcuadataservice:essen-fair-2
        imagePullPolicy: Always
        volumeMounts:
          - name: dataservice-machine-config
            mountPath: /resources/config.json
            subPath: config.json
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
      - name: oisp-iot-agent
        env:
          - name: OISP_DEVICE_ID
            value: "urn:ngsi-ld:assetv5:2:55"
          - name: OISP_DEVICE_NAME
            value: "urn:ngsi-ld:assetv5:2:55"
          - name: OISP_GATEWAY_ID
            value: "urn:ngsi-ld:assetv5:2:55"
          - name: OISP_DEVICE_ACTIVATION_CODE
            valueFrom:
              secretKeyRef:
                key: activation-code
                name: opc-ms-watercut-1-global-devices-secret
        volumeMounts:
          - name: oisp-devices-config-volume
            mountPath: /volume/config
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        image: docker.io/ibn40/oisp-iot-agent:v2.4.2
        imagePullPolicy: Always
        ports:
          - containerPort: 41234
            hostPort: 41234
          - containerPort: 7070
            hostPort: 7070
      - name: oisp-token-operator
        image: ibn40/oisp-token-operator:latest
        imagePullPolicy: Always
        env:
          - name: OISP_API_ROOT
            value: https://development.industry-fusion.com/oisp/v1/api
          - name: USERNAME
            value: factory_admin@industry-fusion.com
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: oisp-password-secret
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
    volumes:
      - name: oisp-devices-config-volume
        configMap:
          name: opc-ms-watercut-1-global-devices-config
          items:
            - key: config.json
              path: config.json
      - name: dataservice-machine-config
        configMap:
          name: opc-ms-watercut-1-app-config
          items:
          - key: config.json
            path: config.json
    imagePullSecrets:
      - name: regcred
    # nodeSelector:
    #   kubernetes.io/hostname: m-3a07708c-8356-460a-81d4-0e62619027bf
  brokerProperties: {}
  capacity: 1