redis:
  storage:
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 50m
      memory: 100Mi
externalRegistry: docker.io
hostAliases:
  ip: "192.168.46.136"
  hostname: "keycloak.local"
alerta:
  externalPath: /
  externalHostname: alerta.local

certmanager:
  secret: selfsigned-cert-tls
  issuer: letsencrypt-self

emqx:
  replicas: 1
  externalHostname: mqtt.local
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
mqtt:
  bridge:
    port: 3025
    url: mqtt-bridge