redis:
  storage:
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 50m
      memory: 100Mi
externalRegistry: docker.io


alerta:
  externalPath: /
  externalHostname: alerta.local

certmanager:
  secret: selfsigned-cert-tls
  issuer: letsencrypt-self

emqx:
  replicas: 1  
  externalHostname: mqtt.local
  resources:
    requests:
      memory: "2Gi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "250m"

mqtt:
  bridge:
    port: 3025
    url: mqtt-bridge
