apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    {{- include "svc.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_API_URL: {{ .Values.config.nextPublicApiUrl | quote }}
  NODE_ENV: "production"
  HOSTNAME: "0.0.0.0"
