environments:
  default:
    values:
    - environment/default.yaml
    - common.gotmpl
    - common.yaml
  production:
    values:
    - environment/production.yaml
    - common.gotmpl
    - common.yaml
---
releases:
- name: mongodb
  labels:
    order: first
    app: mongodb
  chart: ./charts/mongodb
  namespace: {{ .Values.namespace }}
  values:
  - values.yaml.gotmpl
- name: icsdb
  labels:
    order: second
    app: icsdb
  needs:
  - mongodb
  chart: ./charts/icsdb
  namespace: {{ .Values.namespace }}
  values:
  - values.yaml.gotmpl
- name: fleetmanager
  labels:
    order: second
    app: fleetmanager
  needs:
  - mongodb
  chart: ./charts/fleetmanager
  namespace: {{ .Values.namespace }}
  values:
  - values.yaml.gotmpl
- name: if50
  labels:
    order: second
    app: if50
  chart: ./charts/if50
  namespace: {{ .Values.namespace }}
  values:
  - values.yaml.gotmpl
- name: factory50
  labels:
    order: second
    app: factory50
  chart: ./charts/factory50
  namespace: {{ .Values.namespace }}
  values:
  - values.yaml.gotmpl