environments:
  default:
    values:
    - environment/default.yaml
    - common.gotmpl
    - common.yaml
  production:
    values:
    - environment/production.yaml
    - common.gotmpl
    - common.yaml
---
releases:
# - name: icsdb
#   labels:
#     order: second
#     app: icsdb
#   needs:
#   - mongodb
#   chart: ./charts/icsdb
#   namespace: {{ .Values.namespace }}
#   values:
#   - values.yaml.gotmpl
- name: factory50
  labels:
    order: second
    app: factory50
  chart: ./charts/factory50
  namespace: {{ .Values.namespace }}
  values:
  - values.yaml.gotmpl
- name: fleet50
  labels:
    order: second
    app: fleet50
  chart: ./charts/fleet50
  namespace: {{ .Values.namespace }}
  values:
  - values.yaml.gotmpl
- name: icid
  labels:
    order: first
    app: icid
  chart: ./charts/icid
  namespace: {{ .Values.namespace }}
  values:
  - values.yaml.gotmpl
- name: fleet50prod
  labels:
    order: second
    app: fleet50_prod
  chart: ./charts/fleet50_prod
  namespace: {{ .Values.namespace }}
  values:
  - values.yaml.gotmpl
- name: factory50
  labels:
    order: second
    app: factory50_prod
  chart: ./charts/factory50_prod
  namespace: {{ .Values.namespace }}
  values:
  - values.yaml.gotmpl
- name: icid
  labels:
    order: first
    app: icid_prod
  chart: ./charts/icid_prod
  namespace: {{ .Values.namespace }}
  values:
  - values.yaml.gotmpl
- name: ifric-platform
  labels:
    order: second
    app: ifric-platform
  chart: ./charts/ifricplatform
  namespace: ifric-platform
  values:
  - values.yaml.gotmpl
- name: passport-viewer
  labels:
    order: second
    app: passport-viewer
  chart: ./charts/productpassviewer
  namespace: digital-product-passport
  values:
  - values.yaml.gotmpl
- name: ifric-registry
  labels:
    order: second
    app: ifric-registry
  chart: ./charts/ifricregistry
  namespace: ifric-registry-service
  values:
  - values.yaml.gotmpl
# - name: ifric-platform-temp
#   labels:
#     order: second
#     app: ifric-platform-temp
#   chart: ./charts/ifricplatformtemp
#   namespace: ifric-platform
#   values:
#   - values.yaml.gotmpl
- name: template-sandbox
  labels:
    order: second
    app: template-sandbox
  chart: ./charts/templatesandbox
  namespace: template-sandbox
  values:
  - values.yaml.gotmpl
