{{- $secret := (lookup "v1" "Secret" .Release.Namespace "alerta") -}}
apiVersion: v1
kind: Secret
metadata:
  name: alerta
type: Opaque
stringData:
  url: {{ .Values.alerta.url }}
  {{- if $secret }}
  accesskey: {{ $secret.data.accesskey | toString | b64dec }}
  {{- else }}
  accesskey: {{ .Values.alerta.accesskey | toString }}
  {{- end }}