apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-manager-nginx
data:
  config: |
    server {
      auth_basic "Private";
      auth_basic_user_file /etc/nginx/.htpasswd;
      listen 80;
      listen 3080;
      root /usr/share/nginx/html;
      index index.html;
      location / {
        try_files $uri $uri/;
      }
      location /fleetmanager/ {
        index /fleetmanager/index.html;
        try_files $uri$args $uri$args/ $uri/ /fleetmanager/index.html;
      }
      gzip on;
    }