{{- if .Values.opcua.configuration.enabled }}
apiVersion: {{ printf "%s/%s" .Values.crds.group .Values.crds.version }}
kind: Configuration
metadata:
  name: {{ .Values.opcua.configuration.name }}
spec:
  discoveryHandler:
    name: opcua
    discoveryDetails: |+
      opcuaDiscoveryMethod: 
        standard:
          discoveryUrls: 
          {{- toYaml .Values.opcua.configuration.discoveryDetails.discoveryUrls | nindent 10 }}
      applicationNames:
        action: {{ .Values.opcua.configuration.discoveryDetails.applicationNames.action }}
        {{- if .Values.opcua.configuration.discoveryDetails.applicationNames.items}}
        items:
        {{- toYaml .Values.opcua.configuration.discoveryDetails.applicationNames.items | nindent 8 }}
        {{- else }}
        items: []
        {{- end }}

  {{- if .Values.opcua.configuration.brokerPod1.image.repository }}      
  brokerSpec:
    {{- if .Values.opcua.configuration.brokerPod1.image.repository }}
    brokerPodSpec:
      restartPolicy: {{ .Values.opcua.configuration.pod.restartPolicy }}
      containers:
      - name: {{ .Values.opcua.configuration.brokerPod1.name }}
        {{- if .Values.opcua.configuration.brokerPod1.env }}
        env:
          {{- range $key, $val := .Values.opcua.configuration.brokerPod1.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
        {{- end }}
        {{- with .Values.opcua.configuration.brokerPod1.envFrom}}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ printf "%s:%s" .Values.opcua.configuration.brokerPod1.image.repository .Values.opcua.configuration.brokerPod1.image.tag | quote }}
        imagePullPolicy: {{ .Values.opcua.configuration.brokerPod1.image.pullPolicy }}
        resources:
          requests:
            {{`"{{PLACEHOLDER}}"`}} : "1"
          limits:
            {{`"{{PLACEHOLDER}}"`}} : "1"
        {{- if .Values.opcua.configuration.brokerPod1.volumeMounts }}
        volumeMounts:
        {{- with .Values.opcua.configuration.brokerPod1.volumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
      - name: {{ .Values.opcua.configuration.brokerPod2.name }}
        {{- if .Values.opcua.configuration.brokerPod2.env }}
        env:
          {{- range $key, $val := .Values.opcua.configuration.brokerPod2.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
        {{- end }}
        {{- with .Values.opcua.configuration.brokerPod2.envFrom}}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        {{- with .Values.opcua.configuration.brokerPod2.volumeMounts}}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        securityContext:
        {{- with .Values.opcua.configuration.brokerPod2.securityContext}}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ printf "%s:%s" .Values.opcua.configuration.brokerPod2.image.repository .Values.opcua.configuration.brokerPod2.image.tag | quote }}
        imagePullPolicy: {{ .Values.opcua.configuration.brokerPod2.image.pullPolicy }}
        ports:
        {{- with .Values.opcua.configuration.brokerPod2.ports}}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      {{- with .Values.opcua.configuration.pod.volumes}}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- if .Values.opcua.configuration.brokerProperties }}
  brokerProperties:
  {{- range $key, $val := .Values.opcua.configuration.brokerProperties }}
  {{- $key | nindent 4 }}: {{ $val | quote }}
  {{- end }}
  {{- else }}
  brokerProperties: {}
  {{- end }}
  capacity: {{ .Values.opcua.configuration.capacity }}
{{- end }}
{{- end }}

---

apiVersion: v1
data:
  config.json: |
    {
       "fusionopcuadataservice": {
           "specification": [
              {
                  "node_id": "ns=4",
                  "identifier": "i=39",
                  "parameter": "filter-v0.1-filter-runtime-machine-state"
              },
              {
                  "node_id": "ns=4",
                  "identifier": "i=40",
                  "parameter": "base-objects-v0.1-power-supply-runtime-electric-power"
              },
              {
                  "node_id": "ns=4",
                  "identifier": "i=24",
                  "parameter": "filter-v0.1-filter-runtime-operating-hours"
              }
           ]
       }
     }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opc-ms-watercut-1-app-config

---

apiVersion: v1
data:
  config.json: |
    {
                "data_directory": "./data",
                "listeners": {
                        "rest_port": 8000,
                        "udp_port": 41234,
                        "tcp_port": 7070
                },
                "receivers": {
                        "udp_port": 41235,
                        "udp_address": "127.0.0.1"
                },
                "logger": {
                        "level": "info",
                        "path": "/tmp/",
                        "max_size": 134217728
                },
                "connector": {
                        "rest": {
                                "host": "development.industry-fusion.com",
                                "port": 443,
                                "protocol": "https",
                                "strictSSL": false,
                                "timeout": 30000,
                                "proxy": {
                                        "host": false,
                                        "port": false
                                }
                        },
                        "mqtt": {
                                "host": "development.industry-fusion.com",
                                "port": 8883,
                                "websockets": false,
                                "qos": 1,
                                "retain": false,
                                "secure": true,
                                "retries": 5,
                                "strictSSL": false,
                                "sparkplugB": true,
                                "version": "spBv1.0"        
                        }
                }
        }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opc-ms-watercut-1-global-devices-config

---

apiVersion: v1
stringData:
  activation-code: Bagq8zgU
kind: Secret
metadata:
  creationTimestamp: null
  name: opc-ms-watercut-1-global-devices-secret
  namespace: oisp-devices

---

{{- end }}