
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devices-account
  namespace: devices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devices-role
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devices-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devices-role
subjects:
  - kind: ServiceAccount
    name: devices-account
    namespace: devices

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iff-onboarding-controller
  labels:
    app: iff-onboarding-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iff-onboarding-controller
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iff-onboarding-controller
    spec:
      serviceAccountName: devices-account
      restartPolicy: Always
      containers:
        - name: iff-onboarding-controller
          image: {{ .Values.controller.image }}
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
          - name: FACTORY_MONGO_URL
            valueFrom:
              secretKeyRef:
                name: factory-mongo-secret
                key: factoryMongoDbUrl
          - name: FACTORY_MONGO_DB_NAME
            value: {{ .Values.controller.factoryMongoDbName }}
      imagePullSecrets:
        - name: regcred


---
apiVersion: v1
kind: Secret
metadata:
  name: factory-mongo-secret
type: Opaque
data:
  factoryMongoDbUrl: {{ .Values.secrets.factoryMongoDbUrl }}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mongoinserts.myorg.io
spec:
  group: myorg.io
  names:
    kind: MongoInsert
    plural: mongoinserts
    singular: mongoinsert
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                db:
                  type: string
                collection:
                  type: string
                document:
                  type: object