{{- if .Values.opcua.configuration.enabled }}
apiVersion: {{ printf "%s/%s" .Values.crds.group .Values.crds.version }}
kind: Configuration
metadata:
  name: {{ .Values.opcua.configuration.name }}
spec:
  discoveryHandler:
    name: opcua
    discoveryDetails: |+
      opcuaDiscoveryMethod: 
        standard:
          discoveryUrls: 
          {{- toYaml .Values.opcua.configuration.discoveryDetails.discoveryUrls | nindent 10 }}
      applicationNames:
        action: {{ .Values.opcua.configuration.discoveryDetails.applicationNames.action }}
        {{- if .Values.opcua.configuration.discoveryDetails.applicationNames.items}}
        items:
        {{- toYaml .Values.opcua.configuration.discoveryDetails.applicationNames.items | nindent 8 }}
        {{- else }}
        items: []
        {{- end }}

  brokerSpec:
    brokerPodSpec:
      restartPolicy: Always
      containers:
      - name: fusionopcuadataservice
        env:
          - name: OISP_URL
            value: "127.0.0.1"
          - name: OISP_PORT
            value: "7070"
          - name: OPC_USERNAME
            value: ""
          - name: OPC_PASSWORD
            value: ""
          - name: OISP_API_ROOT
            value: https://development.industry-fusion.com/oisp/v1/api
          - name: USERNAME
            value: factory_admin@industry-fusion.com
          - name: OISP_DEVICE_ID
            value: "urn:ngsi-ld:assetv5:2:46"
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: oisp-password-secret
        image: docker.io/ibn40/fusionopcuadataservice:essen-fair-2
        imagePullPolicy: Always
        resources:
          requests:
            {{`"{{PLACEHOLDER}}"`}} : "1"
          limits:
            {{`"{{PLACEHOLDER}}"`}} : "1"
        volumeMounts:
          - name: dataservice-machine-config
            mountPath: /resources/config.json
            subPath: config.json
      - name: oisp-iot-agent
        env:
          - name: OISP_DEVICE_ID
            value: "urn:ngsi-ld:assetv5:2:46"
          - name: OISP_DEVICE_NAME
            value: "urn:ngsi-ld:assetv5:2:46"
          - name: OISP_GATEWAY_ID
            value: "urn:ngsi-ld:assetv5:2:46"
          - name: OISP_DEVICE_ACTIVATION_CODE
            valueFrom:
              secretKeyRef:
                key: activation-code
                name: opc-ms-watercut-1-global-devices-secret
        volumeMounts:
          - name: oisp-devices-config-volume
            mountPath: /volume/config
        securityContext:
          privileged: true
          capabilities:
            drop: ["ALL"]
        image: docker.io/ibn40/oisp-iot-agent:v2.4.2
        imagePullPolicy: Always
        ports:
          - containerPort: 41234
            hostPort: 41234
          - containerPort: 7070
            hostPort: 7070
      volumes:
        - name: oisp-devices-config-volume
          configMap:
            name: opc-ms-watercut-1-global-devices-config
            items:
              - key: config.json
                path: config.json
        - name: dataservice-machine-config
          configMap:
            name: opc-ms-watercut-1-app-config
            items:
            - key: config.json
              path: config.json
      imagePullSecrets:
        - name: regcred
  brokerProperties: {}
  capacity: 1

{{- end }}

---

apiVersion: v1
data:
  config.json: |
    {
       "fusionopcuadataservice": {
           "specification": [
              {
                  "node_id": "ns=4",
                  "identifier": "i=39",
                  "parameter": "filter-v0.1-filter-runtime-machine-state"
              },
              {
                  "node_id": "ns=4",
                  "identifier": "i=40",
                  "parameter": "base-objects-v0.1-power-supply-runtime-electric-power"
              },
              {
                  "node_id": "ns=4",
                  "identifier": "i=24",
                  "parameter": "filter-v0.1-filter-runtime-operating-hours"
              }
           ]
       }
     }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opc-ms-watercut-1-app-config

---

apiVersion: v1
data:
  config.json: |
    {
                "data_directory": "./data",
                "listeners": {
                        "rest_port": 8000,
                        "udp_port": 41234,
                        "tcp_port": 7070
                },
                "receivers": {
                        "udp_port": 41235,
                        "udp_address": "127.0.0.1"
                },
                "logger": {
                        "level": "info",
                        "path": "/tmp/",
                        "max_size": 134217728
                },
                "connector": {
                        "rest": {
                                "host": "development.industry-fusion.com",
                                "port": 443,
                                "protocol": "https",
                                "strictSSL": false,
                                "timeout": 30000,
                                "proxy": {
                                        "host": false,
                                        "port": false
                                }
                        },
                        "mqtt": {
                                "host": "development.industry-fusion.com",
                                "port": 8883,
                                "websockets": false,
                                "qos": 1,
                                "retain": false,
                                "secure": true,
                                "retries": 5,
                                "strictSSL": false,
                                "sparkplugB": true,
                                "version": "spBv1.0"        
                        }
                }
        }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opc-ms-watercut-1-global-devices-config

---

apiVersion: v1
stringData:
  activation-code: Bagq8zgU
kind: Secret
metadata:
  creationTimestamp: null
  name: opc-ms-watercut-1-global-devices-secret
  namespace: oisp-devices

---