name: Deploy

on:
  workflow_dispatch:
    inputs:
      APPS:
        description: 'Space-separated list of apps to deploy/upgrade, leave empty to deploy everything'
        required: false
        default: ''
        type: string
      NAMESPACE:
        description: 'Namespace to deploy'
        required: true
        type: string
      DOCKER_REGISTRY:
        description: 'Name of the docker registry'
        required: false
        default: ibn40
        type: string
      DOCKER_TAG:
        description: 'Docker tag to use in the deployment'
        required: false
        default: 'latest'
        type: string
      PULL_SECRET_CREDENTIALS:
        description: 'Name of the secret in cluster that contains docker registry credentials'
        required: false
        default: 'regcred'
        type: string
      CLUSTER:
        description: 'Tag of the deployer image with the Kubernetes cluster config'
        required: true
        type: string
  workflow_call:
    inputs:
      APPS:
        description: 'Space-separated list of apps to deploy/upgrade, leave empty to deploy everything'
        required: false
        default: ''
        type: string
      NAMESPACE:
        description: 'Namespace to deploy'
        required: true
        type: string
      DOCKER_REGISTRY: 
        description: 'Name of the docker registry'
        required: false
        default: ibn40
        type: string
      DOCKER_TAG:
        description: 'Docker tag to use in the deployment'
        required: false
        default: 'latest'
        type: string
      PULL_SECRET_CREDENTIALS:
        description: 'Name of the secret in cluster that contains docker registry credentials'
        required: false
        default: 'regcred'
        type: string
      CLUSTER:
        description: 'Tag of the deployer image with the Kubernetes cluster config'
        required: true
        type: string
    secrets:
      PRIVATE_GITHUB_TOKEN:
        description: 'Token to use to clone the repositories'
        required: true
      S3_URL:
        description: 'S3 url to use in the cluster'
        required: false
      S3_ACCESS_KEY:
        description: 'S3 access key to use in the cluster'
        required: false
      S3_SECRET_KEY:
        description: 'S3 secret key to use in the cluster'
        required: false
      HUB_TOKEN:
        description: ''
        required: false
      GATEWAY_TOKEN:
        description: ''
        required: false
      ALERTA_KEY_DEV:
        description: ''
        required: false
      FACTORY_MONGO_URL_DEV:
        description: ''
        required: false
      USERNAME:
        description: ''
        required: false
      PASSWORD:
        description: ''
        required: false
      ICID_MONGO_URL_DEV:
        description: ''
        required: false
      ICID_NAMESPACE:
        description: ''
        required: false


jobs:
  clone-repo:
    runs-on: private-2
    steps:
      - uses: actions/checkout@v3
        with:
          repository: IndustryFusion/GitOpsRepo.git
          ref: main
          path: GitOpsRepo
          #token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
  deploy-action:
    needs: clone-repo
    runs-on: private-2
    container:
      image: ibn40/deployer:${{ inputs.CLUSTER }}
      options: --user root
      volumes:
        - ${{ github.workspace }}/GitOpsRepo:/home/deployer/GitOpsRepo
    steps:
      - name: Deploy
        run: |
          helm plugin list
          #export NAMESPACE="${{ inputs.NAMESPACE }}"
          cd /home/deployer/GitOpsRepo/helm
          #bash install_operators.sh
          APPS="${{ inputs.APPS }}"
          LABEL_ARG=""
          for app in ${APPS}; do
            echo "Adding app: ${app} to deployment"
            LABEL_ARG="${LABEL_ARG} -l app=${app}"
          done
          echo "Deploying with selector: ${LABEL_ARG}"
          helmfile ${LABEL_ARG} apply \
            --set mainRepo=${{ inputs.DOCKER_REGISTRY }} \
            --set mainVersion=${{ inputs.DOCKER_TAG }} \
            --set namespace=${{ inputs.NAMESPACE }} \
            --set pullSecretCredentials=${{ inputs.PULL_SECRET_CREDENTIALS }} \
            --set factory50.githubToken="${{ secrets.HUB_TOKEN }}" \
            --set factory50.gatewayToken="${{ secrets.GATEWAY_TOKEN }}" \
            --set factory50.s3AccessKey="${{ secrets.S3_ACCESS_KEY }}" \
            --set factory50.s3SecretKey="${{ secrets.S3_SECRET_KEY }}" \
            --set factory50.alertaKey="${{ secrets.ALERTA_KEY_DEV }}" \
            --set factory50.mongoUrl="${{ secrets.FACTORY_MONGO_URL_DEV }}" \
            --set passport_creator.githubToken="${{ secrets.HUB_TOKEN }}" \
            --set passport_creator.s3AccessKey="${{ secrets.S3_ACCESS_KEY }}" \
            --set passport_creator.s3SecretKey="${{ secrets.S3_SECRET_KEY }}" \
            --set fleet50.githubToken="${{ secrets.HUB_TOKEN }}" \
            --set fleet50.s3AccessKey="${{ secrets.S3_ACCESS_KEY }}" \
            --set fleet50.s3SecretKey="${{ secrets.S3_SECRET_KEY }}" \
            --set fleet50.username="${{ secrets.USERNAME }}" \
            --set fleet50.password="${{ secrets.PASSWORD }}" \
            --set icid.mongoUrl="${{ secrets.ICID_MONGO_URL_DEV }}" \
            --set icid.namespace="${{ secrets.ICID_NAMESPACE }}"
