name: Deploy

on:
  workflow_dispatch:
    inputs:
      APPS:
        description: 'Space-separated list of apps to deploy/upgrade, leave empty to deploy everything'
        required: false
        default: ''
        type: string
      NAMESPACE:
        description: 'Namespace to deploy'
        required: false
        default: 'iff50'
        type: string
      DOCKER_REGISTRY:
        description: 'Name of the docker registry'
        required: false
        default: ibn40
        type: string
      DOCKER_TAG:
        description: 'Docker tag to use in the deployment'
        required: false
        default: 'latest'
        type: string
      PULL_SECRET_CREDENTIALS:
        description: 'Name of the secret in cluster that contains docker registry credentials'
        required: false
        default: 'regcred'
        type: string
  workflow_call:
    inputs:
      APPS:
        description: 'Space-separated list of apps to deploy/upgrade, leave empty to deploy everything'
        required: false
        default: ''
        type: string
      NAMESPACE:
        description: 'Namespace to deploy'
        required: true
        type: string
      DOCKER_REGISTRY: 
        description: 'Name of the docker registry'
        required: false
        default: ibn40
        type: string
      DOCKER_TAG:
        description: 'Docker tag to use in the deployment'
        required: false
        default: 'latest'
        type: string
      PULL_SECRET_CREDENTIALS:
        description: 'Name of the secret in cluster that contains docker registry credentials'
        required: false
        default: 'regcred'
        type: string
      IFF_DEV_DPP_IFRIC_CLUSTER:
        description: 'Name of the Kubernetes cluster'
        required: false
        default: 'YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCnByZWZlcmVuY2VzOiB7fQpjdXJyZW50LWNvbnRl
eHQ6IGNsdXN0ZXItYWRtaW5ASUZGLURFVi1EUFAtSUZSSUMKY2x1c3RlcnM6Ci0gY2x1c3RlcjoK
ICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpR
MEZVUlMwdExTMHRDazFKU1VaRlZFTkRRWFp0WjBGM1NVSkJaMGxWU0hsaU5XSkJSa2hLV2pjMlNs
WXZURFpMTmtaNFduRjVTMmwzZDBSUldVcExiMXBKYUhaalRrRlJSVXdLUWxGQmQwWlVSVlJOUWtW
SFFURlZSVUYzZDB0aE0xWnBXbGhLZFZwWVVteGpla0ZsUm5jd2VVNUVRVEZOZWtGM1QwUk5lRTFx
WkdGR2R6QjZUa1JCTVFwTmFtZDNUMFJOZUUxcVpHRk5RbFY0UlhwQlVrSm5UbFpDUVUxTlEyMTBN
Vmx0Vm5saWJWWXdXbGhOZDJkblNXbE5RVEJIUTFOeFIxTkpZak5FVVVWQ0NrRlJWVUZCTkVsRFJI
ZEJkMmRuU1V0QmIwbERRVkZETm1JeFVXOWFMeXRGTDNoa0x6QjFSV2d5YkU4MWJYWnliVlJaWjFN
MEsxRnBiVFpTVGpRME1GRUtPWEJ4TTA1dFVuaHBjelZ1TkdKVFVXSmpTRVJ1Y2tWVGNtRnlhbFJw
Vkc5dmFHRjBkbVY0VlhaRVRFYzVWbE5TUTNwMWNsUnNhbWxWYlRWck5pOWtTZ28wT0VVeE5sUjFh
azhyYkVFemRpOXFVeTkxWjJ0WkswVnhZV28zTlhKalQzSkJSa2c0YTJkRmJYWnZjelJ6ZW5RelpY
bDVWMWQxYVVsa1ltSnJUWEJGQ2poaVNUbEJObTVJYkRWV1dEY3hiWGsxVTJwRlYzZGpTa0ZDU1Vk
cGNVWlJjWGxpUlRjMFRGcHJjMlpLUWxGMFVGRXZaSFpKVW1kaEwyOWxSMmxEU1RJS2RIZEtjbXRv
UzJKb1dtbFRVeXRvUm5ock5sSkdlRFl4YTJWVU9ISlhaRWR6UkdWcVVVMVhVMW8zTTJsckwyMVlR
M2hhVjJkU1NpczFTRXRDT0d0b1V3cFllRk5ET1VSNmVHSjNOVGc1ZGpSeWFsZGtOM1Z0UTNodlUy
ZEVRMnhEVFdrNWNVOUdjekJ5VjI1bU5YSk9RMWRYZURGQ1ZFOTBUazA1U1ZWamQwWTJDaTlOTW10
MWNUWTFOVlZaY0hnNVFWbzBhR3c0VjNKR2VtNUVOVFJCU1dzdk9YTTVhVUpsUmxBeGFtWkVUR3M0
VDB0VU1UaEVXVTFEU25ZNFJsbFBjRlVLVTA5aFdWQm5RbVJ1WWtsNVJYRTNUVzh4YkU5RUwxSlhU
M0J4Y1ZSaU0wa3dSVGRFUTA5MVRsQjVRalpQZEhKb1ozVjNTSEpSYjFaNU1XNXdaVlZpVEFweFkz
cFFabGhPU2tOTmFHMDVNREpZUjBaRlVteEpVRVJ3YjNCNmVXUm5iVTVNUkM5WFRreGlhMUJvU1M5
VE5HMVFkV1pwVEhGTVNtcDJhRmxsVmpoWkNtaE9XVlJtWkVWYVF6bGFjM3AzWVVNNVJYSjBXRTlE
WVc1M2EwSjRPRWRGVTJWRGRuSm1NM0ZpVEV4SlMzQXJiVGM1V0V4TVYzZE1ZVVpyVW1GVE1tc0th
RWwxVkRRelZFcG9ZV3RQUXpoUWNrbERWM2hKUTBOWFYwcGFibVZQU0ZselMyRjJZaTlOYVdKMFFr
eHplR3AwY2tkclRqSXhPR1paVFhSUGEwRkxRZ3BIVVVsRVFWRkJRbTh4YTNkV2VrRldRbWRPVmto
U1JVVkVha0ZOWjJkd2NtUlhTbXhqYlRWc1pFZFdlazFCTkVkQk1WVmtSSGRGUWk5M1VVVkJkMGxE
Q25CRVFWQkNaMDVXU0ZKTlFrRm1PRVZDVkVGRVFWRklMMDFDTUVkQk1WVmtSR2RSVjBKQ1VXZFdh
VlJPUkcxVGJGZDNWVU5oYlVGYWVsWnljMFZoY2s0S2JGUkJUa0puYTNGb2EybEhPWGN3UWtGUmMw
WkJRVTlEUVdkRlFVWm1URWRrUTJoUlprSjBWbGhIWjIwd05WWnVWMHhxUTBSNmJGaFZTRzV5T0VK
M09BcE1jVTkxZW1wTWVsUjJTMGxOTW5wcGVUSlhXV0kxWXpKelkyTTFORVJTUm5aRk5qTndUMFpI
Y1ZWamNVZFBlVEF4YzJsRVpYa3ZOM0JsWXpaQ0wwMW9DbTUyV21ObmNVSkNUMjQxTjNwT1NqUnFZ
WEJtSzFGcFFtdEdXR3BaZUhWQmRESkxlRGxVVkdwVEsweEljMFpITXpsSWVIQnRWMkprYTA1U01q
RmlSRGdLT1hSWWQyY3ZUVkJGTTBjeFEyZ3dSMmxSVDJodFYzWktkQ3MzZEVWeFZ6WkdSbEJITTJR
MUt6VnZPRzU1UTFrM1UySnNNWGt5TVdvNVpEUlhLekZVVlFvNUsxaFhjSEp1UkcwM2NXaHdWM1pp
ZWxRck9VWXpMM0IxT1RoeE9VTXdjMFpaYjFkVGRrODJPR2N5WVZWTFozWmFUbFZwTVRGSWVGSTVh
VEo1V0ZwT0NrbEVlVUZvV1ZFM2VXSmxUQ3MyTkdWdVNuQkxiMXBMVTNoNFRXbE9RbFZ0YkRScFZt
RlhVekUzUnpKSFlUazBNa055VldNeVVtWnNURTF0ZVVaek1VMEtSa2RuVUVjMFFsTk1Va0pWWjNS
emNHVkRSekZ0VkdkMGRtUlFRMkZGUmpKNlVWRkpVaTlEVldRNVZ6VXlUVkJrUVVKcFNVNVRPRTFT
UzI1TVowWXliQXA0ZGxsSU5XNXdPWGRsWjBVM1ptb3hSV1EwTkhoTUwwUTNhM0pLV1hkVk9HWm5V
akYxVDBOeGNWRXlkVzg1T0ZoTFFXcFRaRWcyWkdWMmFYaExiSFF4Q2pONE1rc3ZjM0ZhWXpJd1Vs
azRja3N4YldnclpVbExjbEk0VFVGSGIzcFdOMVV5U2l0aGJtbFRWa3hZYlVkTmVqSkxjamd5VEZO
eE0wRlhhVEJuSzNFS05UVmtRU3RPUjBwdWMwNWxaRkpIV210aVQzSmlXR2RITUhVNGJFbFhVell3
VEZCVVkwNUlObFp5ZHpJNGVVMDNjV1JLUlV4NGJFOVJRWGRrUmtneFZRcGhSSEpRTDBJelMyOXph
bkprWjAxSWJFRm9SRFJwWTNSRVREbHlNVkkxZVdWVFlpczNUVVF3YVZkNFZHRk1kWEJ3Y1VsdlZE
TnFlRTlrWWxsbGNqUmlDbFE1WWxoeVMyODlDaTB0TFMwdFJVNUVJRU5GVWxSSlJrbERRVlJGTFMw
dExTMEsKICAgIHNlcnZlcjogaHR0cHM6Ly9jcC02YmY1ZmM0Mi0wZjA5LTQ0MDctOGI1YS1iYzgz
NTQ4MzllYmQuazhzLmRlLWZyYS5pb25vcy5jb206MTIzNzIKICBuYW1lOiAhIXN0ciBJRkYtREVW
LURQUC1JRlJJQwpjb250ZXh0czoKLSBjb250ZXh0OgogICAgY2x1c3RlcjogISFzdHIgSUZGLURF
Vi1EUFAtSUZSSUMKICAgIHVzZXI6IGNsdXN0ZXItYWRtaW4KICBuYW1lOiBjbHVzdGVyLWFkbWlu
QElGRi1ERVYtRFBQLUlGUklDCnVzZXJzOgotIG5hbWU6IGNsdXN0ZXItYWRtaW4KICB1c2VyOgog
ICAgdG9rZW46IGV5SmhiR2NpT2lKU1V6STFOaUlzSW10cFpDSTZJbGxwZUhGNE1rMWpZVE5pYkVG
a1dsVmpPV3BxVXpCQ2FqaDVlV3hEU3pCd1ZVWnBNVmhsUm5wdlpsRWlmUS5leUpwYzNNaU9pSnJk
V0psY201bGRHVnpMM05sY25acFkyVmhZMk52ZFc1MElpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpY
SjJhV05sWVdOamIzVnVkQzl1WVcxbGMzQmhZMlVpT2lKcmRXSmxMWE41YzNSbGJTSXNJbXQxWW1W
eWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWamNtVjBMbTVoYldVaU9pSmpiSFZ6
ZEdWeUxXRmtiV2x1TFhSdmEyVnVMWE5sWTNKbGRDSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlk
bWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMbTVoYldVaU9pSmpiSFZ6ZEdWeUxX
RmtiV2x1SWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdO
bExXRmpZMjkxYm5RdWRXbGtJam9pT0dKa1l6UTFNMk10TW1ZME1DMDBNMk5oTFRoaVkyUXRabVEx
T1dVMllUSTVNMlEzSWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tdDFZ
bVV0YzNsemRHVnRPbU5zZFhOMFpYSXRZV1J0YVc0aWZRLmN0d0tyLU9tRGI2V3BxYzkybVNBLXdh
anItMlc0WDA5OTNQT1Z4Ry1aaGt4NnQ4VHhrbzFndm91aFZWNVYwcmJWdko2aFM2TWRZUkhPandN
bmhPdFF0SndBZ183VldyaTNHaGpESUtnVHkzdHB6X2ZmUU9IdEY0a3c2dThpclJaSWdoUG12VHB4
aF9YaFUtQ29xTVpVVGlERWdpSm9aZUdvY0dfTWRMZXZMSkxWY1pZekswQkkwMGZuY1hObW5ZZFpI
ZUtSX1JzM0JxWFg4RzJVUS1jMFJ4Q2ZqQ1Vvc2YwQTh4dkg4M2ZJa2gzUDJBOE54MVZMUUVkQk5Z
WGplMlhpUUpNZHdLa0liRnBPYjBNOVRNaHBBanFGV1NMcURTMjMwQ0tfUEE5SFNtSjZ3Q3BueEJN
bXlSdk5zR0NOT1c0MExMaUhlQWc0TDVOYnF1MFBZWmxZYXlmbV9wVHo3cHRialIyaDFSUmxDMDVz
T0hhSFlDYmlPbnhuTzB5Q09VZGZNbHp3UHVpcXRwbnRkUzhOUTNqeldTWEx3SGd6MG9fV3NJa09z
d0daQXVGX2tOYmZMWEM5T2MzU3g1SDc3dHdwaFJWVzVOdy1pdV9KVTZQSDU2WnZHWjFiR3lhRjQ0
UmpId01HaUlCTUJ0NXFMN2VXLUc1cExwNjY1a2JiZ2d3djB6UGVickxUWWtXNHZVdk9GYi1XVnZR
MVdsQm5LVUt4bWMzTktWWVRXRVpUYVdpVHRhYUY1am15QlRMSXoyU3hicEk1V0pxeUI0RG90Q3pO
Y05DdWJlZmRCV3E1Mk9lWFppOXZqOTVPMkxPZVA2LUdwRC10VV9uaHJwOGZ0d3Vfc1QxN0Z6U0VY
X0dCYUpidGh0OUtJNUtmc251V29WTDByRmxKQXlDRVdnCg=='
        type: string
    secrets:
      PRIVATE_GITHUB_TOKEN:
        description: 'Token to use to clone the repositories'
        required: true
      S3_URL:
        description: 'S3 url to use in the cluster'
        required: false
      S3_ACCESS_KEY:
        description: 'S3 access key to use in the cluster'
        required: false
      S3_SECRET_KEY:
        description: 'S3 secret key to use in the cluster'
        required: false
      HUB_TOKEN:
        description: ''
        required: false
      GATEWAY_TOKEN:
        description: ''
        required: false
      ALERTA_KEY_DEV:
        description: ''
        required: false
      FACTORY_MONGO_URL_DEV:
        description: ''
        required: false
      USERNAME:
        description: ''
        required: false
      PASSWORD:
        description: ''
        required: false
      ICID_MONGO_URL_DEV:
        description: ''
        required: false
      ICID_NAMESPACE:
        description: ''
        required: false


jobs:
  clone-repo:
    runs-on: private-2
    steps:
      - uses: actions/checkout@v3
        with:
          repository: IndustryFusion/GitOpsRepo.git
          ref: main
          path: GitOpsRepo
          #token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
  deploy-action:
    needs: clone-repo
    runs-on: private-2
    container:
      image: ibn40/deployer:latest
      options: --user root
      volumes:
        - ${{ github.workspace }}/GitOpsRepo:/home/deployer/GitOpsRepo
    steps:
      - name: Deploy
        run: |
          helm plugin list
          export NAMESPACE="${{ inputs.NAMESPACE }}"
          cd /home/deployer/GitOpsRepo/helm
          bash install_operators.sh
          APPS="${{ inputs.APPS }}"
          LABEL_ARG=""
          for app in ${APPS}; do
            echo "Adding app: ${app} to deployment"
            LABEL_ARG="${LABEL_ARG} -l app=${app}"
          done
          echo "Deploying with selector: ${LABEL_ARG}"
          
          # Decode Kubernetes cluster config from base64
          echo "${{ inputs.IFF_DEV_DPP_IFRIC_CLUSTER }}" | base64 --decode > /tmp/kubeconfig.yaml
          export KUBECONFIG=/tmp/kubeconfig.yaml
          export NAMESPACE=digital-product-passport
                      
          helmfile ${LABEL_ARG} apply \
            --set mainRepo=${{ inputs.DOCKER_REGISTRY }} \
            --set mainVersion=${{ inputs.DOCKER_TAG }} \
            --set namespace=${{ inputs.NAMESPACE }} \
            --set pullSecretCredentials=${{ inputs.PULL_SECRET_CREDENTIALS }} \
            --set factory50.githubToken="${{ secrets.HUB_TOKEN }}" \
            --set factory50.gatewayToken="${{ secrets.GATEWAY_TOKEN }}" \
            --set factory50.s3AccessKey="${{ secrets.S3_ACCESS_KEY }}" \
            --set factory50.s3SecretKey="${{ secrets.S3_SECRET_KEY }}" \
            --set factory50.alertaKey="${{ secrets.ALERTA_KEY_DEV }}" \
            --set factory50.mongoUrl="${{ secrets.FACTORY_MONGO_URL_DEV }}"\
            --set fleet50.githubToken="${{ secrets.HUB_TOKEN }}" \
            --set fleet50.s3AccessKey="${{ secrets.S3_ACCESS_KEY }}" \
            --set fleet50.s3SecretKey="${{ secrets.S3_SECRET_KEY }}" \
            --set fleet50.username="${{ secrets.USERNAME }}" \
            --set fleet50.password="${{ secrets.PASSWORD }}" \
            --set icid.mongoUrl="${{ secrets.ICID_MONGO_URL_DEV }}" \
            --set icid.namespace="${{ secrets.ICID_NAMESPACE }}"
