name: Update Environment Variables

on:
  pull_request:
    types: [opened, edited]

jobs:
  update-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read PR Description
        id: pr_description
        run: |
          echo "PR_DESCRIPTION<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Check Environment Variables Changes
        id: check_env_changes
        run: |
          if [[ "${{ env.PR_DESCRIPTION }}" =~ "Have you added, removed, or modified any environment variables in this PR? (yes/no)" ]]; then
            echo "Yes" > $GITHUB_ENV
          else
            echo "No" > $GITHUB_ENV
            exit 0
          fi

      - name: Extract Added and Removed Variables
        id: extract_vars
        run: |
          echo "${{ env.PR_DESCRIPTION }}" | grep -oP '(?<=\+ ).*' | grep -vE 'ENV_KEY_1|ENV_KEY_2' > added_vars.txt
          echo "${{ env.PR_DESCRIPTION }}" | grep -oP '(?<=- ).*' | grep -vE 'ENV_KEY_3|ENV_KEY_4' > removed_vars.txt
          
          echo "added_vars=$(<added_vars.txt)" >> $GITHUB_ENV
          echo "removed_vars=$(<removed_vars.txt)" >> $GITHUB_ENV

      - name: Update env.template
        run: |
          TEMPLATE_FILE="env.template"
          MOCK_VALUE="mock_value"
          
          # Add new environment variables
          if [[ -n "${{ env.added_vars }}" ]]; then
            for var in ${{ env.added_vars }}; do
              if ! grep -q "^$var=" "$TEMPLATE_FILE"; then
                echo "$var=$MOCK_VALUE" >> "$TEMPLATE_FILE"
              fi
            done
          fi
          
          # Remove environment variables
          if [[ -n "${{ env.removed_vars }}" ]]; then
            for var in ${{ env.removed_vars }}; do
              sed -i "/^$var=/d" "$TEMPLATE_FILE"
            done
          fi

      - name: Commit changes
        run: |
          git config --local user.email "ragunanthan.j@ib-systems.org"
          git config --local user.name "jragunanthan"
          git add env.template
          git commit -m "Update env.template based on PR changes" || echo "No changes to commit"
          git push
