name: PR Check Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  pr-check:
    name: PR Check with JMeter
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JMeter (install JMeter if not already installed)
      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xzf apache-jmeter-5.6.2.tgz
          export JMETER_HOME=$PWD/apache-jmeter-5.6.2
          export PATH=$JMETER_HOME/bin:$PATH

      # Step 3: Run JMeter Tests
      - name: Run JMeter Tests
        run: |
          jmeter -n -t tests/test-plan.jmx -l results/results.jtl
        continue-on-error: true
        id: jmeter-test

      # Step 4: Check for Test Failures
      - name: Check for JMeter Test Failures
        run: |
          if grep "<failure>" results/results.jtl; then
            echo "JMeter Tests Failed"
            exit 1
          else
            echo "All JMeter Tests Passed"
          fi