name: PR Check Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  pr-check:
    name: PR Check with JMeter
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JMeter (install JMeter if not already installed)
      - name: Install JMeter
        run: |
          curl -O https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          sudo mv apache-jmeter-5.6.3 /opt/jmeter
          echo "export PATH=$PATH:/opt/jmeter/bin" >> $GITHUB_ENV
      
      - name: Set executable permissions
        run: chmod +x /opt/jmeter/bin/*
      
      - name: Run JMeter test
        run: /opt/jmeter/bin/jmeter -n -t tests/test-plan.jmx -l results/results.jtl

      - name: Verify results
        run: cat results/results.jtl

      # Step 3: Check for JMeter Test Failures
      - name: Check for JMeter Test Failures
        run: |
          if grep ',false,' results/results.jtl; then
            echo "JMeter Tests Failed"
            exit 1
          else
            echo "All JMeter Tests Passed"
          fi
